
CREATE TABLE CICLOS_CICLO(
    Codigo NUMERIC(5) PRIMARY KEY,
    Nombre VARCHAR(12), 
    Descripcion VARCHAR(50),
    CONSTRAINT REST_CICL_CICL CHECK(Codigo BETWEEN 00000 AND 99999)
);

CREATE TABLE CICLOS_MODULO(
    Codigo NUMERIC(5) PRIMARY KEY, 
    Nombre VARCHAR(26), 
    Num_horas NUMERIC(3) NOT NULL
);

CREATE TABLE CICLOS_TIENEN_MODULOS(
    Codigo_ciclo_tener NUMERIC(5),
    Codigo_modulo_tener NUMERIC(5),
    CONSTRAINT PK_CIC_TIE_MOD PRIMARY KEY (Codigo_ciclo_tener, Codigo_modulo_tener),
    CONSTRAINT FK_CICLO_TIENE FOREIGN KEY (Codigo_ciclo_tener) REFERENCES CICLOS_CICLO (Codigo),
    CONSTRAINT FK_MODULO_TIENE FOREIGN KEY (Codigo_modulo_tener) REFERENCES CICLOS_MODULO (Codigo)
);

CREATE TABLE CICLOS_DEPARTAMENTO(
    Codigo NUMERIC(5) PRIMARY KEY, 
    Dni_profesor VARCHAR(9),
    Nombre VARCHAR(12) null
);

CREATE TABLE CICLOS_PROFESOR(
    Dni VARCHAR(9) PRIMARY KEY, 
    Codigo_departamento NUMERIC(5),
    Telefono NUMERIC(9) NULL,
    Email VARCHAR(25) NULL ,
    Nombre VARCHAR(30) UNIQUE,
    Fecha_Nacimiento DATE NULL,
    CONSTRAINT FK_PROFESOR_DEPARTAMENTO FOREIGN KEY (Codigo_departamento) REFERENCES CICLOS_DEPARTAMENTO (Codigo)
);

CREATE TABLE CICLOS_CURSO(
    Numero VARCHAR(7) NOT NULL,
    Dni_profesor VARCHAR(9) NULL,
    Grupo VARCHAR(4),
    Codigo_ciclo NUMERIC(5),
    Abreviatura VARCHAR(10) UNIQUE,
    CONSTRAINT PK_CICLOS_CURSO PRIMARY KEY (Numero, Grupo, Codigo_ciclo),
    CONSTRAINT FK_DNI_PRO_CUR FOREIGN KEY (Dni_profesor) REFERENCES CICLOS_PROFESOR (Dni),
    CONSTRAINT FK_CURSO_CICLO FOREIGN KEY (Codigo_ciclo) REFERENCES CICLOS_CICLO (Codigo)
);

CREATE TABLE CICLOS_IMPARTIR(
    Codigo_modulo NUMERIC(5),
    Grupo_curso VARCHAR(4),
    Codigo_ciclo NUMERIC(5),
    Numero_curso VARCHAR(7),
    Dni_profesor VARCHAR(9) NOT NULL,
    Numero_horas_semanales NUMERIC(2) NOT NULL,
    CONSTRAINT PK_IMPARTIR_CURSOS PRIMARY KEY (Codigo_modulo, Grupo_curso,  Codigo_ciclo, Numero_curso),
    CONSTRAINT FK_COD_MOD_IMP FOREIGN KEY (Codigo_modulo) REFERENCES CICLOS_MODULO (Codigo),
    CONSTRAINT FK_COD_CICLO_IMP FOREIGN KEY ( Codigo_ciclo) REFERENCES CICLOS_CICLO (Codigo),
    CONSTRAINT FK_GRU_CUR_IMP FOREIGN KEY (Numero_curso, Grupo_curso, Codigo_ciclo ) REFERENCES CICLOS_CURSO (Numero, Grupo, Codigo_ciclo),
    CONSTRAINT FK_DNI_PRO_IMP FOREIGN KEY (Dni_profesor) REFERENCES CICLOS_PROFESOR (Dni)
);

CREATE TABLE CICLOS_ALUMNO(
    Dni VARCHAR(9) PRIMARY KEY,
    Abreviatura_ciclo VARCHAR(10),
    Nombre VARCHAR(38) NOT NULL,
    Email VARCHAR(25), 
    Fecha_nacimiento DATE NOT NULL, 
    Telefono NUMERIC(9), 
    CONSTRAINT FK_GRU_CUR_ALU FOREIGN KEY (Abreviatura_ciclo) REFERENCES CICLOS_CURSO (Abreviatura)
);

CREATE TABLE CICLOS_TRIMESTRE(
    Codigo NUMERIC(5) PRIMARY KEY,
    Nombre VARCHAR(20),
    Fecha_inicio DATE NOT NULL,
    Fecha_final DATE
    
);

CREATE TABLE CICLOS_EVALUAR(
    Codigo_trimestre NUMERIC(5),
    Dni_alumno VARCHAR(9),
    Codigo_modulo NUMERIC(5),
    Nota NUMERIC(2),
    CONSTRAINT PK_CICLOS PRIMARY KEY (Codigo_trimestre, Dni_alumno, Codigo_modulo),
    CONSTRAINT FK_COD_TRI_EVA FOREIGN KEY (Codigo_trimestre) REFERENCES CICLOS_TRIMESTRE (Codigo), 
    CONSTRAINT FK_DNI_ALU_EVA FOREIGN KEY (Dni_alumno) REFERENCES CICLOS_ALUMNO (Dni),
    CONSTRAINT FK_COD_MOD_EVA FOREIGN KEY (Codigo_modulo) REFERENCES CICLOS_MODULO (Codigo)
);

ALTER TABLE CICLOS_DEPARTAMENTO
ADD CONSTRAINT FK_DNI_PRO_DEP FOREIGN KEY (Dni_profesor) REFERENCES CICLOS_PROFESOR (Dni);

