/*CICLOS FORMATIVOS*/
/*1*/
SELECT *
FROM CICLOS_CICLO
WHERE NOMBRE LIKE '%o%';

/*2*/
SELECT NOMBRE,APELLIDOS
FROM CICLOS_ALUMNO
WHERE CICLO LIKE '1SMR_' AND FECHA_NACIMIENTO> '2001-1-1';

/*3*/

/*Mi DDL no tiene la columna de Apellidos, en el nombre se incluyen también los apellidos*/
SELECT NOMBRE,FECHA_NACIMIENTO
FROM CICLOS_PROFESORES
WHERE DEPARTAMENTO=(SELECT DEPARTAMENTO
       FROM CICLOS_PROFESORES
       WHERE NOMBRE='Samuel Hernández')
ORDER BY FECHA_NACIMIENTO DESC;
/*4*/

/*5*/
/*6*/
/*7*/

