
CREATE TABLE LISTAS_PAIS(
    CODIGO INT PRIMARY KEY,
    NOMBRE VARCHAR(50) 
);
CREATE TABLE LISTAS_PROVINCIA_ESTADO(
    COD INT,
    NOMBRE VARCHAR(50),
    COD_PAIS INT,
    CONSTRAINT PK_ESTADO_PROV PRIMARY KEY (COD, COD_PAIS),
    CONSTRAINT FK_ESTADO_PAIS FOREIGN KEY (COD_PAIS) REFERENCES LISTAS_PAIS(CODIGO) ON UPDATE CASCADE
);

CREATE TABLE LISTAS_CIUDAD(
    COD INT,
    NOMBRE VARCHAR(50),
    PROVINCIA_ESTADO INT,
    CONSTRAINT PK_CIUDAD PRIMARY KEY (COD, PROVINCIA_ESTADO),
    CONSTRAINT FK_CIUDAD_ESTADO FOREIGN KEY (PROVINCIA_ESTADO) REFERENCES LISTAS_PROVINCIA_ESTADO(COD) ON UPDATE CASCADE
);

CREATE TABLE LISTAS_ARTISTA(
    COD INT PRIMARY KEY,
    NOMBREARTISTICO VARCHAR(50) UNIQUE,
    COD_CIUDAD INT,
    CONSTRAINT FK_ARTISTA FOREIGN KEY (COD_CIUDAD) REFERENCES LISTAS_CIUDAD(COD) ON UPDATE CASCADE
);

CREATE TABLE LISTAS_GRUPO(
    COD INT PRIMARY KEY, 
    FCREACION DATE NOT NULL,
    FDISOLUCION DATE

);

CREATE TABLE LISTAS_ARTISTAIND(
    COD INT PRIMARY KEY, 
    NOMBREREAL VARCHAR(100) UNIQUE NOT NULL,
    FNAC DATE NOT NULL,
    FMUERTE DATE,
    FOREIGN KEY(COD) REFERENCES LISTAS_ARTISTA(COD)
);

CREATE TABLE LISTAS_GENERO(
    COD INT PRIMARY KEY, 
    NOMBRE VARCHAR(50) UNIQUE
);

CREATE TABLE LISTAS_CANCION(
    COD INT PRIMARY KEY,
    TITULO VARCHAR(50) NOT NULL,
    ANYO NUMERIC(4,0),
    COD_ARTISTA INT NOT NULL,
    FOREIGN KEY(COD_ARTISTA) REFERENCES LISTAS_ARTISTA(COD)
);

CREATE TABLE LISTAS_GENERO_CANCION(
    COD_CANCION INT,
    COD_GENERO INT,
    PRIMARY KEY(COD_CANCION, COD_GENERO),
    FOREIGN KEY(COD_CANCION) REFERENCES LISTAS_CANCION(COD),
    FOREIGN KEY(COD_GENERO) REFERENCES LISTAS_GENERO(COD)
);

CREATE TABLE LISTAS_LISTA(
    COD INT PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    ANYO NUMERIC(4,0) NOT NULL,
    FUENTE VARCHAR(120),
    AUTOR VARCHAR(50)
);

CREATE TABLE LISTAS_POSICION_LISTA(
    COD_CANCION INT,
    COD_LISTA INT,
    POSICION NUMERIC(4) NOT NULL,
    PRIMARY KEY(COD_CANCION, COD_LISTA),
    FOREIGN KEY(COD_CANCION) REFERENCES LISTAS_CANCION(COD),
    FOREIGN KEY(COD_LISTA) REFERENCES LISTAS_LISTA(COD)
);

ALTER TABLE LISTAS_ARTISTAIND ADD CONSTRAINT MORIRDESPUES CHECK (FMUERTE > FNAC);
ALTER TABLE LISTAS_GRUPO ADD CONSTRAINT DISOLVERDESPUES CHECK (FDISOLUCION > FCREACION);
ALTER TABLE LISTAS_POSICION_LISTA ADD CONSTRAINT POSPOSITIVA CHECK (POSICION > 0);
ALTER TABLE LISTAS_LISTA ADD CONSTRAINT ANYOLISTA CHECK (ANYO > 0);

/*
DROP TABLE LISTAS_PAIS CASCADE;
DROP TABLE LISTAS_PROVINCIA_ESTADO CASCADE;
DROP TABLE LISTAS_GENERO CASCADE;
DROP TABLE LISTAS_CIUDAD CASCADE;
DROP TABLE LISTAS_CANCION CASCADE;
DROP TABLE LISTAS_LISTA CASCADE;
DROP TABLE LISTAS_ARTISTA CASCADE;
DROP TABLE LISTAS_GRUPO CASCADE;
DROP TABLE LISTAS_ARTISTAIND CASCADE;
DROP TABLE LISTAS_GENERO_CANCION CASCADE;
DROP TABLE LISTAS_POSICION_LISTA CASCADE;
*/

