/*DDL*/


/*
Lo primero que he hecho ha sido crear todas las secuencias y cambiar las tablas para que funcionen con secuencias (en todas menos en ARTISTASIND y listas_grupo,
ya que los números no son lineales), en el DML y en el DML he quitado los códigos, porque ya no hacen falta

*/


/*Aquí he añadido código como primary key y nombre único*/
CREATE TABLE LISTAS_PAIS(
    CODIGO INT AUTO_INCREMENT  PRIMARY KEY,
	NOMBRE VARCHAR(50) UNIQUE
);

/*
He quitado nom_pais y la pk compuesta que había, he creado un código como PK y creado código país
para que haga referencia a listas_pais. Además he cambiado el nombre de la tabla de LISTAS_ESTADO_PROVINCIA
a LISTAS_PROVINCIA_ESTADO y a todas sus referencias. También hay modificaciones en el DML, porque daba error en el cod_país
de Auckland(línea 217).
*/

CREATE TABLE LISTAS_PROVINCIA_ESTADO(

    COD INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(50),
    COD_PAIS INT,
    CONSTRAINT FK_PROVINCIA_PAIS FOREIGN KEY(COD_PAIS) REFERENCES LISTAS_PAIS(CODIGO)
);

/*
 Aquí he borrado nom_estado_prov y nom_pais, además de la pk que había y la fk. He creado un código
 como PK y una referencia a LISTA_PROVINCIA_ESTADO para relacionarlo con su código
 */

CREATE TABLE LISTAS_CIUDAD(
    COD INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(50),
    PROVINCIA_ESTADO INT REFERENCES LISTAS_PROVINCIA_ESTADO(COD)
);

/*
 Aquí he quitado nom_ciudad, nom_estado_prov y nom_pais, además, he añadido cod_ciudad,
 al código de ciudad, valga la reduncancia
 */
CREATE TABLE LISTAS_ARTISTA(
    COD INT AUTO_INCREMENT PRIMARY KEY,
	NOMBREARTISTICO VARCHAR(50) UNIQUE,
    COD_CIUDAD INT REFERENCES LISTAS_CIUDAD(COD)

);
/*Aquí he hecho cambios en el DML (línea 473)*/
CREATE TABLE LISTAS_GRUPO(
    COD INT PRIMARY KEY,
    FCREACION DATE NOT NULL,
    FDISOLUCION DATE,
    FOREIGN KEY(COD) REFERENCES LISTAS_ARTISTA(COD)
);

/*
 Aquí hay algunos insert que tienen diferente formato de dar la fecha que el formato indicado,
 es decir TO_DATE('17-02-2004','DD/MM/YYYY'); errores en las líneas 516,519,521,523,525
 Además falta añadir una fecha de nacimiento a 'Pablo Monteagudo' (linea 571). Además, para añadir
 los dos últimos inserts he tenido que añadir dos artistas más a la tabla artistas
 */
CREATE TABLE LISTAS_ARTISTAIND(
    COD INT PRIMARY KEY,
    nombreReal VARCHAR(100) UNIQUE not null,
    FNAC DATE not null,
    FMUERTE DATE,
    FOREIGN KEY(COD) REFERENCES LISTAS_ARTISTA(COD)
);

CREATE TABLE LISTAS_GENERO(
    COD INT AUTO_INCREMENT PRIMARY KEY,
	NOMBRE VARCHAR(50) UNIQUE
);

CREATE TABLE LISTAS_CANCION(
    COD INT AUTO_INCREMENT PRIMARY KEY,
	TITULO VARCHAR(50) NOT NULL,
    ANYO NUMERIC(4),
    COD_ARTISTA INT NOT NULL,
    FOREIGN KEY(COD_ARTISTA) REFERENCES LISTAS_ARTISTA(COD)
);

CREATE TABLE LISTAS_GENERO_CANCION(
    COD_CANCION INT,
    COD_GENERO INT,
    PRIMARY KEY(COD_CANCION, COD_GENERO),
    FOREIGN KEY(COD_CANCION) REFERENCES LISTAS_CANCION(COD),
    FOREIGN KEY(COD_GENERO) REFERENCES LISTAS_GENERO(COD)
);

CREATE TABLE LISTAS_LISTA(
    COD INT AUTO_INCREMENT PRIMARY KEY,
	NOMBRE VARCHAR(100) NOT NULL,
    ANYO NUMERIC(4) NOT NULL,
    FUENTE VARCHAR(120),
    AUTOR VARCHAR(50)
);

/*
Aqui he añadido posicion a la primary key compuesta y le he quitado la
restricción única a posición

 */
CREATE TABLE LISTAS_POSICION_LISTA(
    COD_CANCION INT,
    COD_LISTA INT,
    POSICION NUMERIC(4) NOT NULL,
    PRIMARY KEY(COD_CANCION, COD_LISTA,POSICION),
    FOREIGN KEY(COD_CANCION) REFERENCES LISTAS_CANCION(COD),
    FOREIGN KEY(COD_LISTA) REFERENCES LISTAS_LISTA(COD)
);



ALTER TABLE LISTAS_ARTISTAIND ADD CONSTRAINT MORIRDESPUES CHECK (FMUERTE>FNAC);
ALTER TABLE LISTAS_GRUPO ADD CONSTRAINT DISOLVERDESPUES CHECK (FDISOLUCION>FCREACION);
ALTER TABLE LISTAS_POSICION_LISTA ADD CONSTRAINT POSPOSITIVA CHECK (POSICION>0);
ALTER TABLE LISTAS_LISTA ADD CONSTRAINT ANYOLISTA CHECK (ANYO>0);



/*
DROP TABLE LISTAS_PAIS CASCADE CONSTRAINTS;
DROP TABLE LISTAS_PROVINCIA_ESTADO CASCADE CONSTRAINTS;
DROP TABLE LISTAS_GENERO CASCADE CONSTRAINTS;
DROP TABLE LISTAS_CIUDAD CASCADE CONSTRAINTS;
DROP TABLE LISTAS_CANCION CASCADE CONSTRAINTS;
DROP TABLE LISTAS_LISTA CASCADE CONSTRAINTS;
DROP TABLE LISTAS_ARTISTA CASCADE CONSTRAINTS;
DROP TABLE LISTAS_GRUPO CASCADE CONSTRAINTS;
DROP TABLE LISTAS_ARTISTAIND CASCADE CONSTRAINTS;
DROP TABLE LISTAS_GENERO_CANCION CASCADE CONSTRAINTS;
DROP TABLE LISTAS_POSICION_LISTA CASCADE CONSTRAINTS;
*/



/*DML*/





INSERT INTO LISTAS_LISTA (NOMBRE,ANYO,FUENTE,AUTOR) VALUES ('Mejores debuts RollingStone',2020,'https://los40.com/los40/2020/05/21/los40classic/1590052156_938806.html', 'Rolling Stone');
INSERT INTO LISTAS_LISTA (NOMBRE,ANYO,FUENTE,AUTOR) VALUES ('Las 20 imprescindibles de todos los tiempos',2019,'https://www.esquirelat.com/cultura/20-mejores-canciones-de-todos-los-tiempos/', 'Esquire');
INSERT INTO LISTAS_LISTA (NOMBRE,ANYO,FUENTE,AUTOR) VALUES ('Las mejores canciones del siglo',2018,'https://www.lanacion.com','Rolling Stone');
INSERT INTO LISTAS_LISTA (NOMBRE,ANYO,FUENTE,AUTOR) VALUES ('Las 20 mejores canciones pop de la historia',2020,'https://www.timeout.es/madrid/es/musica/las-20-mejores-canciones-pop-de-la-historia','TimeOut');
INSERT INTO LISTAS_LISTA (NOMBRE,ANYO,FUENTE,AUTOR) VALUES ('Las 20 mejores canciones del rock', 2019, 'http://www.lascosasdebravo.com/mejores-canciones-de-la-historia/', 'Alberto Bravo');
INSERT INTO LISTAS_LISTA (NOMBRE,ANYO,FUENTE,AUTOR) VALUES ('Las mejores canciones del rock de la historia segun VH1', 2019, 'https://www.abc.es/cultura/musica/abci-mejores-canciones-rock-historia-segun-201909251817_noticia.html', 'VH1');
INSERT INTO LISTAS_LISTA (NOMBRE,ANYO,FUENTE,AUTOR) VALUES ('Canciones más escuchadas en España en 2020', 2020, 'https://www.elmundo.es/cultura/2020/12/01/5fc60292fdddffdd018b45ab.html', 'Spotify');
INSERT INTO LISTAS_LISTA (NOMBRE,ANYO,FUENTE,AUTOR) VALUES ('Las 100 mejores canciones Country de todos los tiempos - 2020', 2020, 'https://aztechin.com/las-100-mejores-canciones-country-de-todos-los-tiempos/', 'Carlos Mestre');
INSERT INTO LISTAS_LISTA (NOMBRE,ANYO,FUENTE,AUTOR) VALUES ('Temazos frikis made in Spain',2015,'https://www.elespanol.com/social/20170324/203230101_0.html','El Español');
SELECT * FROM LISTAS_LISTA;

INSERT INTO LISTAS_PAIS(NOMBRE) VALUES ('España');
INSERT INTO LISTAS_PAIS(NOMBRE) VALUES ('Senegal');
INSERT INTO LISTAS_PAIS(NOMBRE) VALUES ('Mongolia');
INSERT INTO LISTAS_PAIS(NOMBRE) VALUES ('Estados Unidos');
INSERT INTO LISTAS_PAIS(NOMBRE) VALUES ('Reino Unido');
INSERT INTO LISTAS_PAIS(NOMBRE) VALUES ('Suecia');
INSERT INTO LISTAS_PAIS(NOMBRE) VALUES ('Colombia');
INSERT INTO LISTAS_PAIS(NOMBRE) VALUES ('Trinidad y Tobago');
INSERT INTO LISTAS_PAIS(NOMBRE) VALUES ('Italia');
INSERT INTO LISTAS_PAIS(NOMBRE) VALUES ('Panamá');
INSERT INTO LISTAS_PAIS(NOMBRE) VALUES ('Australia');
INSERT INTO LISTAS_PAIS(NOMBRE) VALUES ('Canadá');
INSERT INTO LISTAS_PAIS(NOMBRE) VALUES ('Noruega');
INSERT INTO LISTAS_PAIS(NOMBRE) VALUES ('Francia');
INSERT INTO LISTAS_PAIS(NOMBRE) VALUES ('Nueva Zelanda');

INSERT INTO LISTAS_PROVINCIA_ESTADO (NOMBRE,COD_PAIS) VALUES ('Gran Londres',5);
INSERT INTO LISTAS_PROVINCIA_ESTADO (NOMBRE,COD_PAIS) VALUES ('Nueva Jersey',5);
INSERT INTO LISTAS_PROVINCIA_ESTADO (NOMBRE,COD_PAIS) VALUES ('Tennessee',4);
INSERT INTO LISTAS_PROVINCIA_ESTADO (NOMBRE,COD_PAIS) VALUES ('Georgia',4);
INSERT INTO LISTAS_PROVINCIA_ESTADO (NOMBRE,COD_PAIS) VALUES ('Oxfordshire',5);
INSERT INTO LISTAS_PROVINCIA_ESTADO (NOMBRE,COD_PAIS) VALUES ('Pensilvania',4);
INSERT INTO LISTAS_PROVINCIA_ESTADO (NOMBRE,COD_PAIS) VALUES ('Gran Machester',5);
INSERT INTO LISTAS_PROVINCIA_ESTADO (NOMBRE,COD_PAIS) VALUES ('Nueva York',4);
INSERT INTO LISTAS_PROVINCIA_ESTADO (NOMBRE,COD_PAIS) VALUES ('Misisipi',4);
INSERT INTO LISTAS_PROVINCIA_ESTADO (NOMBRE,COD_PAIS) VALUES ('Misuri',4);
INSERT INTO LISTAS_PROVINCIA_ESTADO (NOMBRE,COD_PAIS) VALUES ('Indiana',4);
INSERT INTO LISTAS_PROVINCIA_ESTADO (NOMBRE,COD_PAIS) VALUES ('Merseyside',5);
INSERT INTO LISTAS_PROVINCIA_ESTADO (NOMBRE,COD_PAIS) VALUES ('Minesota',4);
INSERT INTO LISTAS_PROVINCIA_ESTADO (NOMBRE,COD_PAIS) VALUES ('Washington',4);
INSERT INTO LISTAS_PROVINCIA_ESTADO (NOMBRE,COD_PAIS) VALUES ('California',4);
INSERT INTO LISTAS_PROVINCIA_ESTADO (NOMBRE,COD_PAIS) VALUES ('Washington D. C.',4);
INSERT INTO LISTAS_PROVINCIA_ESTADO (NOMBRE,COD_PAIS) VALUES ('Estocolmo',6);
INSERT INTO LISTAS_PROVINCIA_ESTADO (NOMBRE,COD_PAIS) VALUES ('Virginia',4);
INSERT INTO LISTAS_PROVINCIA_ESTADO (NOMBRE,COD_PAIS) VALUES ('Texas',4);
INSERT INTO LISTAS_PROVINCIA_ESTADO (NOMBRE,COD_PAIS) VALUES ('Míchigan',4);
/*He cambiado el código país de 16 (que no existía) a 15 (Nueva Zelanda)*/
INSERT INTO LISTAS_PROVINCIA_ESTADO (NOMBRE,COD_PAIS) VALUES ('Auckland',15);
INSERT INTO LISTAS_PROVINCIA_ESTADO (NOMBRE,COD_PAIS) VALUES ('Puerto Rico',4);
INSERT INTO LISTAS_PROVINCIA_ESTADO (NOMBRE,COD_PAIS) VALUES ('West Yorkshire',5);
INSERT INTO LISTAS_PROVINCIA_ESTADO (NOMBRE,COD_PAIS) VALUES ('Ontario',13);
INSERT INTO LISTAS_PROVINCIA_ESTADO (NOMBRE,COD_PAIS) VALUES ('Atlántico',7);
INSERT INTO LISTAS_PROVINCIA_ESTADO (NOMBRE,COD_PAIS) VALUES ('Oslo',14);
INSERT INTO LISTAS_PROVINCIA_ESTADO (NOMBRE,COD_PAIS) VALUES ('Hawái',4);
INSERT INTO LISTAS_PROVINCIA_ESTADO (NOMBRE,COD_PAIS) VALUES ('Isla de Francia',15);
INSERT INTO LISTAS_PROVINCIA_ESTADO (NOMBRE,COD_PAIS) VALUES ('Florida',4);
INSERT INTO LISTAS_PROVINCIA_ESTADO (NOMBRE,COD_PAIS) VALUES ('Irlanda del Norte',5);
INSERT INTO LISTAS_PROVINCIA_ESTADO (NOMBRE,COD_PAIS) VALUES ('Oregón',4);
INSERT INTO LISTAS_PROVINCIA_ESTADO (NOMBRE,COD_PAIS) VALUES ('Antioquia',7);
INSERT INTO LISTAS_PROVINCIA_ESTADO (NOMBRE,COD_PAIS) VALUES ('Piamonte',9);
INSERT INTO LISTAS_PROVINCIA_ESTADO (NOMBRE,COD_PAIS) VALUES ('Granada',1);
INSERT INTO LISTAS_PROVINCIA_ESTADO (NOMBRE,COD_PAIS) VALUES ('Panamá',11);
INSERT INTO LISTAS_PROVINCIA_ESTADO (NOMBRE,COD_PAIS) VALUES ('Victoria',12);
INSERT INTO LISTAS_PROVINCIA_ESTADO (NOMBRE,COD_PAIS) VALUES ('Kentucky',4);
INSERT INTO LISTAS_PROVINCIA_ESTADO (NOMBRE,COD_PAIS) VALUES ('Tennessee',4);
INSERT INTO LISTAS_PROVINCIA_ESTADO (NOMBRE,COD_PAIS) VALUES ('Alabama',4);
INSERT INTO LISTAS_PROVINCIA_ESTADO (NOMBRE,COD_PAIS) VALUES ('Arkansas',4);
INSERT INTO LISTAS_PROVINCIA_ESTADO (NOMBRE,COD_PAIS) VALUES ('Madrid',1);
INSERT INTO LISTAS_PROVINCIA_ESTADO (NOMBRE,COD_PAIS) VALUES ('Tarragona',1);
INSERT INTO LISTAS_PROVINCIA_ESTADO (NOMBRE,COD_PAIS) VALUES ('Valencia',1);
INSERT INTO LISTAS_PROVINCIA_ESTADO (NOMBRE,COD_PAIS) VALUES ('Dundgovi',3);
INSERT INTO LISTAS_PROVINCIA_ESTADO (NOMBRE,COD_PAIS) VALUES ('Sevilla',1);
INSERT INTO LISTAS_PROVINCIA_ESTADO (NOMBRE,COD_PAIS) VALUES ('Girona',1);
INSERT INTO LISTAS_PROVINCIA_ESTADO (NOMBRE,COD_PAIS) VALUES ('Dakar',2);
INSERT INTO LISTAS_PROVINCIA_ESTADO (NOMBRE,COD_PAIS) VALUES ('Las Palmas de Gran Canaria',1);
INSERT INTO LISTAS_PROVINCIA_ESTADO (NOMBRE,COD_PAIS) VALUES ('Barcelona',1);

INSERT INTO LISTAS_CIUDAD (NOMBRE,PROVINCIA_ESTADO) VALUES ('Bexleyheath',1);
INSERT INTO LISTAS_CIUDAD (NOMBRE,PROVINCIA_ESTADO) VALUES ('Basildon',2);
INSERT INTO LISTAS_CIUDAD (NOMBRE,PROVINCIA_ESTADO) VALUES ('Memphis',3);
INSERT INTO LISTAS_CIUDAD (NOMBRE,PROVINCIA_ESTADO) VALUES ('Atlanta',4);
INSERT INTO LISTAS_CIUDAD (NOMBRE,PROVINCIA_ESTADO) VALUES ('Abingdon',5);
INSERT INTO LISTAS_CIUDAD (NOMBRE,PROVINCIA_ESTADO) VALUES ('Athens',4);
INSERT INTO LISTAS_CIUDAD (NOMBRE,PROVINCIA_ESTADO) VALUES ('Londres',1);
INSERT INTO LISTAS_CIUDAD (NOMBRE,PROVINCIA_ESTADO) VALUES ('Reading',6);
INSERT INTO LISTAS_CIUDAD (NOMBRE,PROVINCIA_ESTADO) VALUES ('Manchester',7);
INSERT INTO LISTAS_CIUDAD (NOMBRE,PROVINCIA_ESTADO) VALUES ('Queens',8);
INSERT INTO LISTAS_CIUDAD (NOMBRE,PROVINCIA_ESTADO) VALUES ('Tupelo',9);
INSERT INTO LISTAS_CIUDAD (NOMBRE,PROVINCIA_ESTADO) VALUES ('San Luis',10);
INSERT INTO LISTAS_CIUDAD (NOMBRE,PROVINCIA_ESTADO) VALUES ('Gary',11);
INSERT INTO LISTAS_CIUDAD (NOMBRE,PROVINCIA_ESTADO) VALUES ('McComb',9);
INSERT INTO LISTAS_CIUDAD (NOMBRE,PROVINCIA_ESTADO) VALUES ('Liverpool',12);
INSERT INTO LISTAS_CIUDAD (NOMBRE,PROVINCIA_ESTADO) VALUES ('Duluth',13);
INSERT INTO LISTAS_CIUDAD (NOMBRE,PROVINCIA_ESTADO) VALUES ('Clarksdale',9);
INSERT INTO LISTAS_CIUDAD (NOMBRE,PROVINCIA_ESTADO) VALUES ('Albany',4);
INSERT INTO LISTAS_CIUDAD (NOMBRE,PROVINCIA_ESTADO) VALUES ('Aberdeen',14);
INSERT INTO LISTAS_CIUDAD (NOMBRE,PROVINCIA_ESTADO) VALUES ('Hawthorne',15);
INSERT INTO LISTAS_CIUDAD (NOMBRE,PROVINCIA_ESTADO) VALUES ('Washington D. C.',16);
INSERT INTO LISTAS_CIUDAD (NOMBRE,PROVINCIA_ESTADO) VALUES ('Enfield',1);
INSERT INTO LISTAS_CIUDAD (NOMBRE,PROVINCIA_ESTADO) VALUES ('Estocolmo',17);
INSERT INTO LISTAS_CIUDAD (NOMBRE,PROVINCIA_ESTADO) VALUES ('Brixton',1);
INSERT INTO LISTAS_CIUDAD (NOMBRE,PROVINCIA_ESTADO) VALUES ('Portsmouth',18);
INSERT INTO LISTAS_CIUDAD (NOMBRE,PROVINCIA_ESTADO) VALUES ('Brooklyn',8);
INSERT INTO LISTAS_CIUDAD (NOMBRE,PROVINCIA_ESTADO) VALUES ('Compton',15);
INSERT INTO LISTAS_CIUDAD (NOMBRE,PROVINCIA_ESTADO) VALUES ('Fort Worth',19);
INSERT INTO LISTAS_CIUDAD (NOMBRE,PROVINCIA_ESTADO) VALUES ('Houston',19);
INSERT INTO LISTAS_CIUDAD (NOMBRE,PROVINCIA_ESTADO) VALUES ('Hounslow',1);
INSERT INTO LISTAS_CIUDAD (NOMBRE,PROVINCIA_ESTADO) VALUES ('Detroit',20);
INSERT INTO LISTAS_CIUDAD (NOMBRE,PROVINCIA_ESTADO) VALUES ('Nueva York',8);
INSERT INTO LISTAS_CIUDAD (NOMBRE,PROVINCIA_ESTADO) VALUES ('Auckland',21);
INSERT INTO LISTAS_CIUDAD (NOMBRE,PROVINCIA_ESTADO) VALUES ('San Juan',22);
INSERT INTO LISTAS_CIUDAD (NOMBRE,PROVINCIA_ESTADO) VALUES ('Halifax',23);
INSERT INTO LISTAS_CIUDAD (NOMBRE,PROVINCIA_ESTADO) VALUES ('Santa Bárbara',15);
INSERT INTO LISTAS_CIUDAD (NOMBRE,PROVINCIA_ESTADO) VALUES ('London',24);
INSERT INTO LISTAS_CIUDAD (NOMBRE,PROVINCIA_ESTADO) VALUES ('Barranquilla',25);
INSERT INTO LISTAS_CIUDAD (NOMBRE,PROVINCIA_ESTADO) VALUES ('Oslo',26);
INSERT INTO LISTAS_CIUDAD (NOMBRE,PROVINCIA_ESTADO) VALUES ('Honolulú',27);
INSERT INTO LISTAS_CIUDAD (NOMBRE,PROVINCIA_ESTADO) VALUES ('París',28);
INSERT INTO LISTAS_CIUDAD (NOMBRE,PROVINCIA_ESTADO) VALUES ('Bay City',20);
INSERT INTO LISTAS_CIUDAD (NOMBRE,PROVINCIA_ESTADO) VALUES ('Mineápolis',13);
INSERT INTO LISTAS_CIUDAD (NOMBRE,PROVINCIA_ESTADO) VALUES ('Newark',2);
INSERT INTO LISTAS_CIUDAD (NOMBRE,PROVINCIA_ESTADO) VALUES ('Orlando',29);
INSERT INTO LISTAS_CIUDAD (NOMBRE,PROVINCIA_ESTADO) VALUES ('Los Ángeles',15);
INSERT INTO LISTAS_CIUDAD (NOMBRE,PROVINCIA_ESTADO) VALUES ('Belfast',16);
INSERT INTO LISTAS_CIUDAD (NOMBRE,PROVINCIA_ESTADO) VALUES ('Malibú',15);
INSERT INTO LISTAS_CIUDAD (NOMBRE,PROVINCIA_ESTADO) VALUES ('Long Branch',2);
INSERT INTO LISTAS_CIUDAD (NOMBRE,PROVINCIA_ESTADO) VALUES ('Toronto',24);
INSERT INTO LISTAS_CIUDAD (NOMBRE,PROVINCIA_ESTADO) VALUES ('Portland',31);
INSERT INTO LISTAS_CIUDAD (NOMBRE,PROVINCIA_ESTADO) VALUES ('New Rochelle',8);
INSERT INTO LISTAS_CIUDAD (NOMBRE,PROVINCIA_ESTADO) VALUES ('Medellín',32);
INSERT INTO LISTAS_CIUDAD (NOMBRE,PROVINCIA_ESTADO) VALUES ('Turín',33);
INSERT INTO LISTAS_CIUDAD (NOMBRE,PROVINCIA_ESTADO) VALUES ('Salinas',22);
INSERT INTO LISTAS_CIUDAD (NOMBRE,PROVINCIA_ESTADO) VALUES ('Ítrabo',34);
INSERT INTO LISTAS_CIUDAD (NOMBRE,PROVINCIA_ESTADO) VALUES ('Almirante Sur',22);
INSERT INTO LISTAS_CIUDAD (NOMBRE,PROVINCIA_ESTADO) VALUES ('Río Abajo',35);
INSERT INTO LISTAS_CIUDAD (NOMBRE,PROVINCIA_ESTADO) VALUES ('Mount Martha',36);
INSERT INTO LISTAS_CIUDAD (NOMBRE,PROVINCIA_ESTADO) VALUES ('Butcker Hollow',37);
INSERT INTO LISTAS_CIUDAD (NOMBRE,PROVINCIA_ESTADO) VALUES ('Poteet',19);
INSERT INTO LISTAS_CIUDAD (NOMBRE,PROVINCIA_ESTADO) VALUES ('Kosse',19);
INSERT INTO LISTAS_CIUDAD (NOMBRE,PROVINCIA_ESTADO) VALUES ('Nashville',38);
INSERT INTO LISTAS_CIUDAD (NOMBRE,PROVINCIA_ESTADO) VALUES ('Mount Olive',39);
INSERT INTO LISTAS_CIUDAD (NOMBRE,PROVINCIA_ESTADO) VALUES ('Rosine',37);
INSERT INTO LISTAS_CIUDAD (NOMBRE,PROVINCIA_ESTADO) VALUES ('Sherman',19);
INSERT INTO LISTAS_CIUDAD (NOMBRE,PROVINCIA_ESTADO) VALUES ('Dickenson County',18);
INSERT INTO LISTAS_CIUDAD (NOMBRE,PROVINCIA_ESTADO) VALUES ('Littlefield',19);
INSERT INTO LISTAS_CIUDAD (NOMBRE,PROVINCIA_ESTADO) VALUES ('Sevierville',38);
INSERT INTO LISTAS_CIUDAD (NOMBRE,PROVINCIA_ESTADO) VALUES ('Bakersfield',15);
INSERT INTO LISTAS_CIUDAD (NOMBRE,PROVINCIA_ESTADO) VALUES ('Itawamba',9);
INSERT INTO LISTAS_CIUDAD (NOMBRE,PROVINCIA_ESTADO) VALUES ('Vidor',19);
INSERT INTO LISTAS_CIUDAD (NOMBRE,PROVINCIA_ESTADO) VALUES ('Winchester',18);
INSERT INTO LISTAS_CIUDAD (NOMBRE,PROVINCIA_ESTADO) VALUES ('Kingsland',40);
INSERT INTO LISTAS_CIUDAD (NOMBRE,PROVINCIA_ESTADO) VALUES ('Madrid',41);
INSERT INTO LISTAS_CIUDAD (NOMBRE,PROVINCIA_ESTADO) VALUES ('Tortosa',42);
INSERT INTO LISTAS_CIUDAD (NOMBRE,PROVINCIA_ESTADO) VALUES ('Sagunto',43);
INSERT INTO LISTAS_CIUDAD (NOMBRE,PROVINCIA_ESTADO) VALUES ('Mandalgobi',44);
INSERT INTO LISTAS_CIUDAD (NOMBRE,PROVINCIA_ESTADO) VALUES ('Sevilla',45);
INSERT INTO LISTAS_CIUDAD (NOMBRE,PROVINCIA_ESTADO) VALUES ('Sant Jordi Desvalls',46);
INSERT INTO LISTAS_CIUDAD (NOMBRE,PROVINCIA_ESTADO) VALUES ('Dakar',47);
INSERT INTO LISTAS_CIUDAD (NOMBRE,PROVINCIA_ESTADO) VALUES ('Gran Canaria',48);
INSERT INTO LISTAS_CIUDAD (NOMBRE,PROVINCIA_ESTADO) VALUES ('Barcelona',49);

INSERT INTO LISTAS_ARTISTA (NOMBREARTISTICO,COD_CIUDAD) VALUES ('Kate Bush',1);
INSERT INTO LISTAS_ARTISTA (NOMBREARTISTICO,COD_CIUDAD) VALUES ('Depeche Mode',2);
INSERT INTO LISTAS_ARTISTA (NOMBREARTISTICO,COD_CIUDAD) VALUES ('The Box Tops',3);
INSERT INTO LISTAS_ARTISTA (NOMBREARTISTICO,COD_CIUDAD) VALUES ('OutKast',4);
INSERT INTO LISTAS_ARTISTA (NOMBREARTISTICO,COD_CIUDAD) VALUES ('Radiohead',5);
INSERT INTO LISTAS_ARTISTA (NOMBREARTISTICO,COD_CIUDAD) VALUES ('The B-52’s',6);
INSERT INTO LISTAS_ARTISTA (NOMBREARTISTICO,COD_CIUDAD) VALUES ('Kanye West',4);
INSERT INTO LISTAS_ARTISTA (NOMBREARTISTICO,COD_CIUDAD) VALUES ('The Clash',7);
INSERT INTO LISTAS_ARTISTA (NOMBREARTISTICO,COD_CIUDAD) VALUES ('Lil Nas X',4);
INSERT INTO LISTAS_ARTISTA (NOMBREARTISTICO,COD_CIUDAD) VALUES ('Taylor Swift',8);
INSERT INTO LISTAS_ARTISTA (NOMBREARTISTICO,COD_CIUDAD) VALUES ('The Smiths',9);
INSERT INTO LISTAS_ARTISTA (NOMBREARTISTICO,COD_CIUDAD) VALUES ('Ramones',10);
INSERT INTO LISTAS_ARTISTA (NOMBREARTISTICO,COD_CIUDAD) VALUES ('Elvis Presley',11);
INSERT INTO LISTAS_ARTISTA (NOMBREARTISTICO,COD_CIUDAD) VALUES ('Led Zeppelin',7);
INSERT INTO LISTAS_ARTISTA (NOMBREARTISTICO,COD_CIUDAD) VALUES ('R.E.M',6);
INSERT INTO LISTAS_ARTISTA (NOMBREARTISTICO,COD_CIUDAD) VALUES ('Chuck Berry',12);
INSERT INTO LISTAS_ARTISTA (NOMBREARTISTICO,COD_CIUDAD) VALUES ('Run-DMC',10);
INSERT INTO LISTAS_ARTISTA (NOMBREARTISTICO,COD_CIUDAD) VALUES ('The Jackson 5',13);
INSERT INTO LISTAS_ARTISTA (NOMBREARTISTICO,COD_CIUDAD) VALUES ('The Sex Pistols',7);
INSERT INTO LISTAS_ARTISTA (NOMBREARTISTICO,COD_CIUDAD) VALUES ('Britney Spears',14);
INSERT INTO LISTAS_ARTISTA (NOMBREARTISTICO,COD_CIUDAD) VALUES ('The Beatles',15);
INSERT INTO LISTAS_ARTISTA (NOMBREARTISTICO,COD_CIUDAD) VALUES ('The Jimi Hendrix Experience',7);
INSERT INTO LISTAS_ARTISTA (NOMBREARTISTICO,COD_CIUDAD) VALUES ('Bob Dylan',16);
INSERT INTO LISTAS_ARTISTA (NOMBREARTISTICO,COD_CIUDAD) VALUES ('Sam Cooke',17);
INSERT INTO LISTAS_ARTISTA (NOMBREARTISTICO,COD_CIUDAD) VALUES ('The Who',7);
INSERT INTO LISTAS_ARTISTA (NOMBREARTISTICO,COD_CIUDAD) VALUES ('Ray Charles',18);
INSERT INTO LISTAS_ARTISTA (NOMBREARTISTICO,COD_CIUDAD) VALUES ('Nirvana',19);
INSERT INTO LISTAS_ARTISTA (NOMBREARTISTICO,COD_CIUDAD) VALUES ('The Beach Boys',20);
INSERT INTO LISTAS_ARTISTA (NOMBREARTISTICO,COD_CIUDAD) VALUES ('Aretha Franklin',3);
INSERT INTO LISTAS_ARTISTA (NOMBREARTISTICO,COD_CIUDAD) VALUES ('Marvin Gaye',21);
INSERT INTO LISTAS_ARTISTA (NOMBREARTISTICO,COD_CIUDAD) VALUES ('John Lennon',7);
INSERT INTO LISTAS_ARTISTA (NOMBREARTISTICO,COD_CIUDAD) VALUES ('The Rolling Stones',7);
INSERT INTO LISTAS_ARTISTA (NOMBREARTISTICO,COD_CIUDAD) VALUES ('Amy Winehouse',22);
INSERT INTO LISTAS_ARTISTA (NOMBREARTISTICO,COD_CIUDAD) VALUES ('Robyn',23);
INSERT INTO LISTAS_ARTISTA (NOMBREARTISTICO,COD_CIUDAD) VALUES ('David Bowie',24);
INSERT INTO LISTAS_ARTISTA (NOMBREARTISTICO,COD_CIUDAD) VALUES ('Missy Elliot',25);
INSERT INTO LISTAS_ARTISTA (NOMBREARTISTICO,COD_CIUDAD) VALUES ('LCD Soundsystem',26);
INSERT INTO LISTAS_ARTISTA (NOMBREARTISTICO,COD_CIUDAD) VALUES ('Gnarls Barkley',4);
INSERT INTO LISTAS_ARTISTA (NOMBREARTISTICO,COD_CIUDAD) VALUES ('Kendrick Lamar',27);
INSERT INTO LISTAS_ARTISTA (NOMBREARTISTICO,COD_CIUDAD) VALUES ('Kelly Clarkson',28);
INSERT INTO LISTAS_ARTISTA (NOMBREARTISTICO,COD_CIUDAD) VALUES ('Beyoncé',29);
INSERT INTO LISTAS_ARTISTA (NOMBREARTISTICO,COD_CIUDAD) VALUES ('M.I.A.',30);
INSERT INTO LISTAS_ARTISTA (NOMBREARTISTICO,COD_CIUDAD) VALUES ('The White Stripes',31);
INSERT INTO LISTAS_ARTISTA (NOMBREARTISTICO,COD_CIUDAD) VALUES ('Jay-Z',26);
INSERT INTO LISTAS_ARTISTA (NOMBREARTISTICO,COD_CIUDAD) VALUES ('Yeah Yeah Yeahs',32);
INSERT INTO LISTAS_ARTISTA (NOMBREARTISTICO,COD_CIUDAD) VALUES ('Adele',7);
INSERT INTO LISTAS_ARTISTA (NOMBREARTISTICO,COD_CIUDAD) VALUES ('Lorde',33);
INSERT INTO LISTAS_ARTISTA (NOMBREARTISTICO,COD_CIUDAD) VALUES ('The Strokes',32);
INSERT INTO LISTAS_ARTISTA (NOMBREARTISTICO,COD_CIUDAD) VALUES ('Luis Fonsi',34);
INSERT INTO LISTAS_ARTISTA (NOMBREARTISTICO,COD_CIUDAD) VALUES ('Ed Sheeran',35);
INSERT INTO LISTAS_ARTISTA (NOMBREARTISTICO,COD_CIUDAD) VALUES ('Katy Perry',36);
INSERT INTO LISTAS_ARTISTA (NOMBREARTISTICO,COD_CIUDAD) VALUES ('Justin Bieber',37);
INSERT INTO LISTAS_ARTISTA (NOMBREARTISTICO,COD_CIUDAD) VALUES ('Shakira',38);
INSERT INTO LISTAS_ARTISTA (NOMBREARTISTICO,COD_CIUDAD) VALUES ('A-ha',39);
INSERT INTO LISTAS_ARTISTA (NOMBREARTISTICO,COD_CIUDAD) VALUES ('Bruno Mars',40);
INSERT INTO LISTAS_ARTISTA (NOMBREARTISTICO,COD_CIUDAD) VALUES ('Daft Punk',41);
INSERT INTO LISTAS_ARTISTA (NOMBREARTISTICO,COD_CIUDAD) VALUES ('Michael Jackson',13);
INSERT INTO LISTAS_ARTISTA (NOMBREARTISTICO,COD_CIUDAD) VALUES ('Madonna',42);
INSERT INTO LISTAS_ARTISTA (NOMBREARTISTICO,COD_CIUDAD) VALUES ('Prince',43);
INSERT INTO LISTAS_ARTISTA (NOMBREARTISTICO,COD_CIUDAD) VALUES ('Whitney Houston',44);
INSERT INTO LISTAS_ARTISTA (NOMBREARTISTICO,COD_CIUDAD) VALUES ('Backstreet Boys',45);
INSERT INTO LISTAS_ARTISTA (NOMBREARTISTICO,COD_CIUDAD) VALUES ('Lady Gaga',32);
INSERT INTO LISTAS_ARTISTA (NOMBREARTISTICO,COD_CIUDAD) VALUES ('Neil Young and Crazy Horse',46);
INSERT INTO LISTAS_ARTISTA (NOMBREARTISTICO,COD_CIUDAD) VALUES ('Van Morrison',47);
INSERT INTO LISTAS_ARTISTA (NOMBREARTISTICO,COD_CIUDAD) VALUES ('Little Feat',46);
INSERT INTO LISTAS_ARTISTA (NOMBREARTISTICO,COD_CIUDAD) VALUES ('Paul Simon',44);
INSERT INTO LISTAS_ARTISTA (NOMBREARTISTICO,COD_CIUDAD) VALUES ('Dereck and The Dominos',7);
INSERT INTO LISTAS_ARTISTA (NOMBREARTISTICO,COD_CIUDAD) VALUES ('Fleetwood Mac',7);
INSERT INTO LISTAS_ARTISTA (NOMBREARTISTICO,COD_CIUDAD) VALUES ('The Traveling Wilburys',48);
INSERT INTO LISTAS_ARTISTA (NOMBREARTISTICO,COD_CIUDAD) VALUES ('Pink Floyd',7);
INSERT INTO LISTAS_ARTISTA (NOMBREARTISTICO,COD_CIUDAD) VALUES ('Bruce Springsteen',49);
INSERT INTO LISTAS_ARTISTA (NOMBREARTISTICO,COD_CIUDAD) VALUES ('The Band',50);
INSERT INTO LISTAS_ARTISTA (NOMBREARTISTICO,COD_CIUDAD) VALUES ('The Kinks',7);
INSERT INTO LISTAS_ARTISTA (NOMBREARTISTICO,COD_CIUDAD) VALUES ('Lou Reed',26);
INSERT INTO LISTAS_ARTISTA (NOMBREARTISTICO,COD_CIUDAD) VALUES ('Eagles',46);
INSERT INTO LISTAS_ARTISTA (NOMBREARTISTICO,COD_CIUDAD) VALUES ('The Doors',46);
INSERT INTO LISTAS_ARTISTA (NOMBREARTISTICO,COD_CIUDAD) VALUES ('The Kingsmen',51);
INSERT INTO LISTAS_ARTISTA (NOMBREARTISTICO,COD_CIUDAD) VALUES ('Don McLean',52);
INSERT INTO LISTAS_ARTISTA (NOMBREARTISTICO,COD_CIUDAD) VALUES ('Karol G',53);
INSERT INTO LISTAS_ARTISTA (NOMBREARTISTICO,COD_CIUDAD) VALUES ('Fred de Palma',54);
INSERT INTO LISTAS_ARTISTA (NOMBREARTISTICO,COD_CIUDAD) VALUES ('Nio Garcia',34);
INSERT INTO LISTAS_ARTISTA (NOMBREARTISTICO,COD_CIUDAD) VALUES ('Ozuna',34);
INSERT INTO LISTAS_ARTISTA (NOMBREARTISTICO,COD_CIUDAD) VALUES ('Jay Wheeler',55);
INSERT INTO LISTAS_ARTISTA (NOMBREARTISTICO,COD_CIUDAD) VALUES ('Chema Rivas',56);
INSERT INTO LISTAS_ARTISTA (NOMBREARTISTICO,COD_CIUDAD) VALUES ('J Balvin',53);
INSERT INTO LISTAS_ARTISTA (NOMBREARTISTICO,COD_CIUDAD) VALUES ('Bad Bunny',57);
INSERT INTO LISTAS_ARTISTA (NOMBREARTISTICO,COD_CIUDAD) VALUES ('Sech',58);
INSERT INTO LISTAS_ARTISTA (NOMBREARTISTICO,COD_CIUDAD) VALUES ('Tones and I',59);
INSERT INTO LISTAS_ARTISTA (NOMBREARTISTICO,COD_CIUDAD) VALUES ('Kenny Rogers',29);
INSERT INTO LISTAS_ARTISTA (NOMBREARTISTICO,COD_CIUDAD) VALUES ('Loretta Lynn',60);
INSERT INTO LISTAS_ARTISTA (NOMBREARTISTICO,COD_CIUDAD) VALUES ('George Strait',61);
INSERT INTO LISTAS_ARTISTA (NOMBREARTISTICO,COD_CIUDAD) VALUES ('Bob Wills',62);
INSERT INTO LISTAS_ARTISTA (NOMBREARTISTICO,COD_CIUDAD) VALUES ('Glen Campbell',63);
INSERT INTO LISTAS_ARTISTA (NOMBREARTISTICO,COD_CIUDAD) VALUES ('Kitty Wells',63);
INSERT INTO LISTAS_ARTISTA (NOMBREARTISTICO,COD_CIUDAD) VALUES ('Hank Williams',64);
INSERT INTO LISTAS_ARTISTA (NOMBREARTISTICO,COD_CIUDAD) VALUES ('Bill Monroe',65);
INSERT INTO LISTAS_ARTISTA (NOMBREARTISTICO,COD_CIUDAD) VALUES ('Buck Owens',66);
INSERT INTO LISTAS_ARTISTA (NOMBREARTISTICO,COD_CIUDAD) VALUES ('The Stanley Brothers',67);
INSERT INTO LISTAS_ARTISTA (NOMBREARTISTICO,COD_CIUDAD) VALUES ('Waylon Jennings',68);
INSERT INTO LISTAS_ARTISTA (NOMBREARTISTICO,COD_CIUDAD) VALUES ('Dolly Parton',69);
INSERT INTO LISTAS_ARTISTA (NOMBREARTISTICO,COD_CIUDAD) VALUES ('Merle Haggard',70);
INSERT INTO LISTAS_ARTISTA (NOMBREARTISTICO,COD_CIUDAD) VALUES ('Tammy Wynette',71);
INSERT INTO LISTAS_ARTISTA (NOMBREARTISTICO,COD_CIUDAD) VALUES ('Jimmie Rodgers',32);
INSERT INTO LISTAS_ARTISTA (NOMBREARTISTICO,COD_CIUDAD) VALUES ('George Jones',72);
INSERT INTO LISTAS_ARTISTA (NOMBREARTISTICO,COD_CIUDAD) VALUES ('Patsy Cline',73);
INSERT INTO LISTAS_ARTISTA (NOMBREARTISTICO,COD_CIUDAD) VALUES ('Johnny Cash',74);
INSERT INTO LISTAS_ARTISTA (NOMBREARTISTICO,COD_CIUDAD) VALUES ('Aless Gibaja',75);
INSERT INTO LISTAS_ARTISTA (NOMBREARTISTICO,COD_CIUDAD) VALUES ('Karmele Marchante',76);
INSERT INTO LISTAS_ARTISTA (NOMBREARTISTICO,COD_CIUDAD) VALUES ('John Cobra',77);
INSERT INTO LISTAS_ARTISTA (NOMBREARTISTICO,COD_CIUDAD) VALUES ('Pupi Poisson',78);
INSERT INTO LISTAS_ARTISTA (NOMBREARTISTICO,COD_CIUDAD) VALUES ('Kiko Rivera',79);
INSERT INTO LISTAS_ARTISTA (NOMBREARTISTICO,COD_CIUDAD) VALUES ('Flos Mariae',80);
INSERT INTO LISTAS_ARTISTA (NOMBREARTISTICO,COD_CIUDAD) VALUES ('Lory Money',81);
INSERT INTO LISTAS_ARTISTA (NOMBREARTISTICO,COD_CIUDAD) VALUES ('La Ogra',82);
INSERT INTO LISTAS_ARTISTA (NOMBREARTISTICO,COD_CIUDAD) VALUES ('Leticia Sabater',83);
INSERT INTO LISTAS_ARTISTA (NOMBREARTISTICO,COD_CIUDAD) VALUES ('Rodolfo Chikilicuatre',83);
INSERT INTO LISTAS_ARTISTA (NOMBREARTISTICO,COD_CIUDAD) VALUES ('Leticia Maria Sabater Alonso',82);
INSERT INTO LISTAS_ARTISTA (NOMBREARTISTICO,COD_CIUDAD) VALUES ('David Fernandez Ortiz',83);

INSERT INTO LISTAS_GRUPO (COD,FCREACION) VALUES (2,STR_TO_DATE('01-01-1980','%d-%m-%Y'));
INSERT INTO LISTAS_GRUPO (COD,FCREACION) VALUES (3,STR_TO_DATE('01-01-1967','%d-%m-%Y'));
INSERT INTO LISTAS_GRUPO (COD,FCREACION,FDISOLUCION) VALUES (4,STR_TO_DATE('01-01-1992','%d-%m-%Y'),STR_TO_DATE('01-01-2006','%d-%m-%Y'));
INSERT INTO LISTAS_GRUPO (COD,FCREACION,FDISOLUCION) VALUES (5,STR_TO_DATE('01-01-1985','%d-%m-%Y'),null);
INSERT INTO LISTAS_GRUPO (COD,FCREACION,FDISOLUCION) VALUES (6,STR_TO_DATE('01-01-1976','%d-%m-%Y'),null);
INSERT INTO LISTAS_GRUPO (COD,FCREACION,FDISOLUCION) VALUES (8,STR_TO_DATE('01-01-1976','%d-%m-%Y'),STR_TO_DATE('01-01-1986','%d-%m-%Y'));
INSERT INTO LISTAS_GRUPO (COD,FCREACION,FDISOLUCION) VALUES (11,STR_TO_DATE('01-01-1982','%d-%m-%Y'),STR_TO_DATE('01-01-1987','%d-%m-%Y'));
INSERT INTO LISTAS_GRUPO (COD,FCREACION,FDISOLUCION) VALUES (12,STR_TO_DATE('01-01-1974','%d-%m-%Y'),STR_TO_DATE('01-01-1996','%d-%m-%Y'));
INSERT INTO LISTAS_GRUPO (COD,FCREACION,FDISOLUCION) VALUES (14,STR_TO_DATE('01-01-1968','%d-%m-%Y'),STR_TO_DATE('04-12-1980','%d-%m-%Y'));
INSERT INTO LISTAS_GRUPO (COD,FCREACION,FDISOLUCION) VALUES (15,STR_TO_DATE('01-01-1980','%d-%m-%Y'),STR_TO_DATE('01-01-2011','%d-%m-%Y'));
INSERT INTO LISTAS_GRUPO (COD,FCREACION,FDISOLUCION) VALUES (17,STR_TO_DATE('01-01-1981','%d-%m-%Y'),STR_TO_DATE('01-01-2002','%d-%m-%Y'));
INSERT INTO LISTAS_GRUPO (COD,FCREACION,FDISOLUCION) VALUES (18,STR_TO_DATE('01-01-1964','%d-%m-%Y'),STR_TO_DATE('01-01-1990','%d-%m-%Y'));
INSERT INTO LISTAS_GRUPO (COD,FCREACION,FDISOLUCION) VALUES (19,STR_TO_DATE('01-01-1975','%d-%m-%Y'),STR_TO_DATE('01-01-1978','%d-%m-%Y'));
INSERT INTO LISTAS_GRUPO (COD,FCREACION,FDISOLUCION) VALUES (21,STR_TO_DATE('01-01-1960','%d-%m-%Y'),STR_TO_DATE('09-04-1970','%d-%m-%Y'));
INSERT INTO LISTAS_GRUPO (COD,FCREACION,FDISOLUCION) VALUES (22,STR_TO_DATE('01-01-1966','%d-%m-%Y'),STR_TO_DATE('01-01-1970','%d-%m-%Y'));
INSERT INTO LISTAS_GRUPO (COD,FCREACION,FDISOLUCION) VALUES (26,STR_TO_DATE('01-01-1964','%d-%m-%Y'),null);
INSERT INTO LISTAS_GRUPO (COD,FCREACION,FDISOLUCION) VALUES (28,STR_TO_DATE('01-01-1987','%d-%m-%Y'),STR_TO_DATE('01-01-1994','%d-%m-%Y'));
INSERT INTO LISTAS_GRUPO (COD,FCREACION,FDISOLUCION) VALUES (29,STR_TO_DATE('01-01-1961','%d-%m-%Y'),null);
INSERT INTO LISTAS_GRUPO (COD,FCREACION,FDISOLUCION) VALUES (33,STR_TO_DATE('01-01-1962','%d-%m-%Y'),null);
INSERT INTO LISTAS_GRUPO (COD,FCREACION,FDISOLUCION) VALUES (38,STR_TO_DATE('01/01/2003','%d/%m/%Y'), Null);
INSERT INTO LISTAS_GRUPO (COD,FCREACION,FDISOLUCION) VALUES (39,STR_TO_DATE('01/01/2001','%d/%m/%Y'), Null);
INSERT INTO LISTAS_GRUPO (COD,FCREACION,FDISOLUCION) VALUES (44,STR_TO_DATE('14-08-1997','%d-%m-%Y'),STR_TO_DATE('02-02-2011','%d-%m-%Y'));
INSERT INTO LISTAS_GRUPO (COD,FCREACION,FDISOLUCION) VALUES (46,STR_TO_DATE('01-01-2000','%d-%m-%Y'),null);
INSERT INTO LISTAS_GRUPO (COD,FCREACION,FDISOLUCION) VALUES (49,STR_TO_DATE('01-01-1998','%d-%m-%Y'),null);
INSERT INTO LISTAS_GRUPO (COD,FCREACION,FDISOLUCION) VALUES (55,STR_TO_DATE('02-02-1982','%d-%m-%Y'),null);
INSERT INTO LISTAS_GRUPO (COD,FCREACION,FDISOLUCION) VALUES (57,STR_TO_DATE('12-10-1993','%d-%m-%Y'),null);
INSERT INTO LISTAS_GRUPO (COD,FCREACION,FDISOLUCION) VALUES (62,STR_TO_DATE('20-04-1993','%d-%m-%Y'),null);
INSERT INTO LISTAS_GRUPO (COD,FCREACION,FDISOLUCION) VALUES (64,STR_TO_DATE('01-01-1962','%d-%m-%Y'),null);
INSERT INTO LISTAS_GRUPO (COD,FCREACION,FDISOLUCION) VALUES (66,STR_TO_DATE('01-01-1969','%d-%m-%Y'),null);
INSERT INTO LISTAS_GRUPO (COD,FCREACION,FDISOLUCION) VALUES (68,STR_TO_DATE('01-01-1970','%d-%m-%Y'),STR_TO_DATE('01-01-1971','%d-%m-%Y'));
INSERT INTO LISTAS_GRUPO (COD,FCREACION,FDISOLUCION) VALUES (69,STR_TO_DATE('01-01-1967','%d-%m-%Y'),null);
INSERT INTO LISTAS_GRUPO (COD,FCREACION,FDISOLUCION) VALUES (70,STR_TO_DATE('01-01-1988','%d-%m-%Y'),STR_TO_DATE('01-01-1990','%d-%m-%Y'));
/*Aquí he puesto el STR_TO_DATE que faltaba*/
INSERT INTO LISTAS_GRUPO (COD,FCREACION,FDISOLUCION) VALUES (71,STR_TO_DATE('01-01-1965','%d-%m-%Y'),STR_TO_DATE('01-01-1995','%d-%m-%Y'));
INSERT INTO LISTAS_GRUPO (COD,FCREACION,FDISOLUCION) VALUES (73,STR_TO_DATE('01-01-1968','%d-%m-%Y'),STR_TO_DATE('01-01-1999','%d-%m-%Y'));
INSERT INTO LISTAS_GRUPO (COD,FCREACION,FDISOLUCION) VALUES (74,STR_TO_DATE('01-01-1963','%d-%m-%Y'),null);
INSERT INTO LISTAS_GRUPO (COD,FCREACION,FDISOLUCION) VALUES (76,STR_TO_DATE('01-01-1971','%d-%m-%Y'),null);
INSERT INTO LISTAS_GRUPO (COD,FCREACION,FDISOLUCION) VALUES (77,STR_TO_DATE('01-01-1965','%d-%m-%Y'),STR_TO_DATE('01-01-1973','%d-%m-%Y'));
INSERT INTO LISTAS_GRUPO (COD,FCREACION,FDISOLUCION) VALUES (78,STR_TO_DATE('01-01-1959','%d-%m-%Y'),null);
INSERT INTO LISTAS_GRUPO (COD,FCREACION,FDISOLUCION) VALUES (99,STR_TO_DATE('01-01-1946','%d-%m-%Y'),STR_TO_DATE('01-01-1966','%d-%m-%Y'));
INSERT INTO LISTAS_GRUPO (COD,FCREACION,FDISOLUCION) VALUES (114,STR_TO_DATE('12-01-2013','%d-%m-%Y'),null);

INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (1,'Catherine Bush',STR_TO_DATE('30-06-1958','%d-%m-%Y'),null);
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (7,'Kanye Omari West',STR_TO_DATE('08-05-1977','%d-%m-%Y'),null);
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (9,'Montero Lamar Hill',STR_TO_DATE('09-04-1999','%d-%m-%Y'),null);
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (10,'Taylor Alison Swift',STR_TO_DATE('13-12-1989','%d-%m-%Y'),null);
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (13,'Elvis Aaron Presley',STR_TO_DATE('08-01-1935','%d-%m-%Y'),STR_TO_DATE('16-08-1977','%d-%m-%Y'));
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (16,'Charles Anderson Edward Berry',STR_TO_DATE('18-10-1926','%d-%m-%Y'),STR_TO_DATE('18-03-2017','%d-%m-%Y'));
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (20,'Britney Jean Spears',STR_TO_DATE('02-12-1981','%d-%m-%Y'),null);
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (24,'Robert Allen Zimmerman',STR_TO_DATE('24-05-1941','%d-%m-%Y'),null);
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (25,'Samuel Cook',STR_TO_DATE('21-01-1931','%d-%m-%Y'),STR_TO_DATE('11-12-1964','%d-%m-%Y'));
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (27,'Ray Charles Robinson',STR_TO_DATE('23-09-1930','%d-%m-%Y'),STR_TO_DATE('10-06-2004','%d-%m-%Y'));
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (30,'Aretha Louise Franklin',STR_TO_DATE('25-03-1942','%d-%m-%Y'),STR_TO_DATE('16-08-2018','%d-%m-%Y'));
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (31,'Marvin Pentz Gay',STR_TO_DATE('02-04-1939','%d-%m-%Y'),STR_TO_DATE('01-04-1984','%d-%m-%Y'));
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (32,'John Winston Lennon',STR_TO_DATE('09-09-1940','%d-%m-%Y'),STR_TO_DATE('08-12-1980','%d-%m-%Y'));
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (34,'Amy Jade Winehouse',STR_TO_DATE('14/09/1983','%d/%m/%Y'), STR_TO_DATE('23/07/2011','%d/%m/%Y'));
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (35,'Robin Miriam Carlsson',STR_TO_DATE('12/06/1979','%d/%m/%Y'), null);
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (36,'David Robert Jones',STR_TO_DATE('08/01/1947','%d/%m/%Y'), STR_TO_DATE('10/01/2016','%d/%m/%Y'));
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (37,'Melissa Arnette Elliott',STR_TO_DATE('01/07/1971','%d/%m/%Y'),null);
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (40,'Kendric Lamar Duckworth',STR_TO_DATE('17/06/1987','%d/%m/%Y'),null);
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (41,'Kelly Brianne Clarkson',STR_TO_DATE('24/04/1982','%d/%m/%Y'),null);
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (42,'Beyoncé Giselle Knowles-Carter',STR_TO_DATE('04-09-1981','%d-%m-%Y'),null);
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (43,'Mathangi Arulpragasam',STR_TO_DATE('18-07-1975','%d-%m-%Y'),null);
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (45,'Shawn Corey Carter',STR_TO_DATE('04-12-1969','%d-%m-%Y'),null);
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (47,'Adele Laurie Blue Adkins',STR_TO_DATE('05-05-1988','%d-%m-%Y'),null);
/*aqui había error de formato*/
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (48,'Ella Marija Lani Yelich O''Connor',STR_TO_DATE('07/11/1996','%d/%m/%Y'),null);
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (50,'Luis Alfonso Rodríguez López-Cepero',STR_TO_DATE('15-03-1978','%d-%m-%Y'),null);
/*aqui había error de formato*/
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (51,'Edward Christopher Sheeran',STR_TO_DATE('17/02/1991','%d/%m/%Y'),NULL);
/*aqui había error de formato*/
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (52,'Katheryn Elizabeth Hudson',STR_TO_DATE('25/10/1984','%d/%m/%Y'),NULL);
/*aqui había error de formato*/
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (53,'Justin Drew Bieber',STR_TO_DATE('1/03/1994','%d/%m/%Y'),NULL);
/*aqui había error de formato*/
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (54,'Shakira Isabel Mebarak Ripoll',STR_TO_DATE('2/2/1977','%d/%m/%Y'),NULL);
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (56,'Peter Gene Hernández',STR_TO_DATE('08-10-1985','%d-%m-%Y'),NULL);
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (58,'Michael Joseph Jackson',STR_TO_DATE('29-08-1958','%d-%m-%Y'),STR_TO_DATE('25-07-2009','%d-%m-%Y'));
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (59,'Madonna Louise Veronica Ciccone',STR_TO_DATE('16-08-1958','%d-%m-%Y'),null);
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (60,'Prince Rogers Nelson',STR_TO_DATE('07-06-1958','%d-%m-%Y'),STR_TO_DATE('21-04-2016','%d-%m-%Y'));
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (61,'Whitney Elizabeth Houston',STR_TO_DATE('09-08-1963','%d-%m-%Y'),STR_TO_DATE('11-02-2012','%d-%m-%Y'));
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (63,'Stefani Joanne Angelina Germanotta',STR_TO_DATE('28-03-1986','%d-%m-%Y'),null);
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (65,'George Ivan Morrison', STR_TO_DATE('31/08/1945','%d/%m/%Y'), null);
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (67,'Paul Frederic Simon', STR_TO_DATE('01/01/1956','%d/%m/%Y'), null);
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (72,'Bruce Frederick Joseph Springsteen', STR_TO_DATE('23-09-1949','%d-%m-%Y'), null);
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (75,'Lewis Allan Reed', STR_TO_DATE('02-03-1942','%d-%m-%Y'), STR_TO_DATE('27-10-2013','%d-%m-%Y'));
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (79,'Donald McLean II', STR_TO_DATE('02-10-1945','%d-%m-%Y'), null);
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (80,'Carolina Giraldo Navarro', STR_TO_DATE('14-02-1991','%d-%m-%Y'), null);
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (81,'Federico Palana', STR_TO_DATE('03-11-1989','%d-%m-%Y'), null);
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (82,'Luis Antonio Quinones Garcia', STR_TO_DATE('03-04-1989','%d-%m-%Y'), null);
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (83,'Juan Carlos Ozuna Rosado',STR_TO_DATE('13-03-1992','%d-%m-%Y'), null);
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (84,'José Ángel López Martínez', STR_TO_DATE('25-04-1994','%d-%m-%Y'), null);
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (85,'Chema Rivas', STR_TO_DATE('01-01-2001','%d-%m-%Y'), null);
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (86,'José Álvaro Osorio Balvín', STR_TO_DATE('07-05-1985','%d-%m-%Y'), null);
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (87,'Benito Antonio Martínez', STR_TO_DATE('10-03-1994','%d-%m-%Y'), null);
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (88,'Carlos Isaías Morales',STR_TO_DATE('03-12-1993','%d-%m-%Y'), null);
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (89,'Toni Watson', STR_TO_DATE('01-01-1990','%d-%m-%Y'), null);
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (90,'Kenneth Donald Rogers', STR_TO_DATE('21-08-1938','%d-%m-%Y'), STR_TO_DATE('20-03-2020','%d-%m-%Y'));
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (91,'Loretta Webb', STR_TO_DATE('14-04-1932','%d-%m-%Y'), null);
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (92,'George Harvey Strait', STR_TO_DATE('18-05-1952','%d-%m-%Y'), null);
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (93,'James Robert Wills', STR_TO_DATE('06-03-1905','%d-%m-%Y'), STR_TO_DATE('13-05-1975','%d-%m-%Y'));
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (94,'Glen Travis Campbell', STR_TO_DATE('22-04-1936','%d-%m-%Y'), STR_TO_DATE('08-08-2017','%d-%m-%Y'));
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (95,'Ellen Muriel Deason', STR_TO_DATE('30-08-1919','%d-%m-%Y'), STR_TO_DATE('16-07-2012','%d-%m-%Y'));
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (96,'Hiram King Williams', STR_TO_DATE('17-09-1923','%d-%m-%Y'), STR_TO_DATE('01-01-1953','%d-%m-%Y'));
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (97,'William Smith Monroe', STR_TO_DATE('13-09-1911','%d-%m-%Y'), STR_TO_DATE('09-09-1996','%d-%m-%Y'));
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (98,'Alvis Edgar Owens Jr.', STR_TO_DATE('12-08-1929','%d-%m-%Y'), STR_TO_DATE('25-03-2006','%d-%m-%Y'));
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (100,'Waylon Arnold Jennings', STR_TO_DATE('15-06-1937','%d-%m-%Y'), STR_TO_DATE('13-02-2002','%d-%m-%Y'));
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (101,'Dolly Rebecca Parton', STR_TO_DATE('19-01-1946','%d-%m-%Y'), null);
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (102,'Merle Ronald Haggard', STR_TO_DATE('06-04-1937','%d-%m-%Y'), STR_TO_DATE('06-04-2016','%d-%m-%Y'));
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (103,'Virginia Wynette Pugh', STR_TO_DATE('05-05-1942','%d-%m-%Y'), STR_TO_DATE('06-04-1998','%d-%m-%Y'));
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (104,'James Charles Rodgers', STR_TO_DATE('08-09-1897','%d-%m-%Y'), STR_TO_DATE('26-05-1933','%d-%m-%Y'));
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (105,'George Glenn Jones', STR_TO_DATE('12-09-1931','%d-%m-%Y'), STR_TO_DATE('26-04-2013','%d-%m-%Y'));
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (107,'Virginia Patterson Hensley', STR_TO_DATE('08-09-1932','%d-%m-%Y'), STR_TO_DATE('05-03-1963','%d-%m-%Y'));
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (108,'J. R. Cash', STR_TO_DATE('26-02-1932','%d-%m-%Y'), STR_TO_DATE('12-09-2003','%d-%m-%Y'));
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (109,'Aless Gibaja', STR_TO_DATE('19-04-1984','%d-%m-%Y'),null);
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (110,'María del Carmen Marchante Barrobés', STR_TO_DATE('15-09-1946','%d-%m-%Y'),null);
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (111,'Mario Vaquero Garcés', STR_TO_DATE('11-02-1978','%d-%m-%Y'),null);
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (112,'Alberto Zimmer', STR_TO_DATE('01-06-1983','%d-%m-%Y'),null);
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (113,'Francisco José Rivera Pantoja', STR_TO_DATE('09-02-1984','%d-%m-%Y'),null);
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (115,'Dara Dia', STR_TO_DATE('26-12-1978','%d-%m-%Y'),null);
/*Aquí faltaba añadir la fecha de nacimiento*/
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (116,'Pablo Monteagudo', STR_TO_DATE('01-01-2000','%d-%m-%Y'),null);
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (117,'Leticia Maria Sabater Alonso', STR_TO_DATE('21-06-1966','%d-%m-%Y'),null);
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (118,'David Fernandez Ortiz', STR_TO_DATE('24-06-1970','%d-%m-%Y'),null);

INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('Wuthering Heights',1978,1);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('Dreaming of Me',1981,2);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('The Letter',1967,3);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('Player’s Ball',1993,4);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('Creep',1993,5);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('Rock Lobster',1978,6);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('Through the Wire',2003,7);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('White Riot',1977,8);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('Old Town Road',2019,9);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('Tim McGraw',2006,10);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('Hand in Glove',1984,11);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('Blitzkrieg Bop',1976,12);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('Thats All Right',1956,13);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('Good Times Bad Times',1969,14);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('Radio Free Europe',1983,15);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('Maybellene',1956,16);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('Sucker M.C.s/Its Like That',1984,17);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('I Want You Back',1969,18);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('Anarchy in the U.K.',1977,19);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('Baby One More Time',1998,20);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('Yesterday',1965,21);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('Let it be',1968,21);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('Hound Dog',1956,13);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('Purple Haze',1967,22);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('I want to hold your hand',1963,21);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('London Calling',1979,8);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('Blowin in the Wind',1963,24);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('A Change is Gonna Come',1964,25);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('My generation',1965,26);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('What’d I say',1959,27);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('Smells like Teen Spirit',1991,28);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('Hey Jude',1968,21);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('Johnny B. Goode',1959,16);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('Good Vibrations',1970,29);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('Respect',1965,30);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('Whats Going On',1971,31);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('Imagine',1971,32);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('(I Cant Get No) Satisfaction',1965,33);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('Like a Rolling Stone',1965,24);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('Rehab',2006,34);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('Dancing On My Own', 2017,35);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('Blackstar',2015,36);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('Work it', 2002,37);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('All My Friends', 2007,38);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('Crazy', 2006,39);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('Toxic', 2003,20);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('Alright', 2015,40);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('Since U Been Gone', 2004,41);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('Get Ur Freak On', 2001,37);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('Crazy in Love',2003,42);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('Paper Planes',2007,43);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('Seven Nation Army',2003,44);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('Hey Ya!',2003,4);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('99 Problems',2003,45);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('Maps',2003,46);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('Runaway',2010,7);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('Rolling in the deep',2011,47);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('Royals',2013,48);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('Last Nite',2001,49);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('Despacito',2019,50);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('Shape of you',2017,51);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('Firework',2019,52);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('Sorry',2015,53);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('Hips dont lie',2006,54);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('Take on me',1985,55);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('Uptown Funk',2014,56);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('Get Lucky',2013,57);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('Thriller',1982,58);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('Like a Prayer',1989,59);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('When Doves Cry',1984,60);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('Wanna Dance With Somebody',1987,61);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('Everybody',1997,62);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('Poker Face',2008,63);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('Single Ladies',2008,42);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('Powderfinger',1979,64);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('Into the mystic',1970,65);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('Willin',1971,66);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('Space Oddity',1969,36);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('Suspicious Minds',1969,13);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('Baba ORiley',1971,26);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('Brown Sugar',1971,33);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('American Tune',1973,67);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('Layla',1970,68);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('The Chain',1977,69);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('Handle with care',1988,70);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('Shine on you crazy diamond',1975,71);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('Stairway to Heaven',1971,14);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('Thunder Road',1975,72);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('The Weight',1968,73);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('Lola',1970,74);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('A day in the life',1967,21);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('Sweet Jane',1977,75);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('Born to run',1975,72);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('Hotel California',1976,76);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('Light my Fire',1967,77);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('Louie Louie',1963,78);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('Wont get Fooled Again',1971,26);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('Jailhouse Rock',1957,13);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('American Pie',1971,79);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('Tusa',2019,80);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('Se iluminaba',2019,81);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('La Jeepeta - Remix',2020,82);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('Caramelo',2020,83);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('La Curiosidad',2020,84);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('Mil Tequilas',2020,85);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('Morado',2020,86);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('Safaera',2020,87);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('Relación',2020,88);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('Dance Monkey',2020,89);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('The Gambler',1978,90);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('Dont Come Home A Drinkin (With Lovin on Your Mind)',1966,91);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('All My Exs Live in Texas',1987,92);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('New San Antonio Rose',1940,93);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('Witchita Lineman',1968,94);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('It Wasn’t God Who Made Honky Tonk Angels',1952,95);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('Settin’ the Woods on Fire',1952,96);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('Blue Moon of Kentucky',1947,97);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('Ive Got a Tiger By the Tail',1964,98);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('Man of Constant Sorrow',1951,99);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('Mammas, Dont Let Your Babies Grow Up to Be Cowboys',1978,100);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('Jolene',1973,101);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('Mama Tried',1968,102);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('You Dont Know Me',1962,27);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('Stand By Your Man',1968,103);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('Standing on the Corner (Blue Yodel #9)',1930,104);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('He Stopped Loving Her Today',1980,105);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('I’m So Lonesome I Could Cry',1949,96);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('Crazy',1961,107);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('I Walk the Line',1956,108);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('Sexy summer',2004,109);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('Soy un tsunami',2010,110);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('Carol',2012,111);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('Putón verbenero',2015,112);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('Dale',2015,113);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('Amén',2015,114);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('Ola k ase',2013,115);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('Te borro del feisbuh',2015,116);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('La Salchipapa',2016,117);
INSERT INTO LISTAS_CANCION(TITULO,ANYO,COD_ARTISTA) VALUES ('Baila el Chiki Chiki',2017,118);


INSERT INTO LISTAS_GENERO (NOMBRE) VALUES ('Art pop');
INSERT INTO LISTAS_GENERO (NOMBRE) VALUES ('Synth pop');
INSERT INTO LISTAS_GENERO (NOMBRE) VALUES ('Pop');
INSERT INTO LISTAS_GENERO (NOMBRE) VALUES ('Hip-hop');
INSERT INTO LISTAS_GENERO (NOMBRE) VALUES ('Funk');
INSERT INTO LISTAS_GENERO (NOMBRE) VALUES ('Rock Alternativo');
INSERT INTO LISTAS_GENERO (NOMBRE) VALUES ('Grunge');
INSERT INTO LISTAS_GENERO (NOMBRE) VALUES ('Trip-hop');
INSERT INTO LISTAS_GENERO (NOMBRE) VALUES ('New wave');
INSERT INTO LISTAS_GENERO (NOMBRE) VALUES ('Surf punk');
INSERT INTO LISTAS_GENERO (NOMBRE) VALUES ('Punk rock');
INSERT INTO LISTAS_GENERO (NOMBRE) VALUES ('Country');
INSERT INTO LISTAS_GENERO (NOMBRE) VALUES ('Trap');
INSERT INTO LISTAS_GENERO (NOMBRE) VALUES ('Reggae');
INSERT INTO LISTAS_GENERO (NOMBRE) VALUES ('Punk');
INSERT INTO LISTAS_GENERO (NOMBRE) VALUES ('Rock');
INSERT INTO LISTAS_GENERO (NOMBRE) VALUES ('Indie');
INSERT INTO LISTAS_GENERO (NOMBRE) VALUES ('Chamber pop');
INSERT INTO LISTAS_GENERO (NOMBRE) VALUES ('Pop Rock');
INSERT INTO LISTAS_GENERO (NOMBRE) VALUES ('Rock and roll');
INSERT INTO LISTAS_GENERO (NOMBRE) VALUES ('Folk');
INSERT INTO LISTAS_GENERO (NOMBRE) VALUES ('Soul');
INSERT INTO LISTAS_GENERO (NOMBRE) VALUES ('Rhythm and blues');
INSERT INTO LISTAS_GENERO (NOMBRE) VALUES ('Acústico');
INSERT INTO LISTAS_GENERO (NOMBRE) VALUES ('Dance-pop');
INSERT INTO LISTAS_GENERO (NOMBRE) VALUES ('Electro-pop');
INSERT INTO LISTAS_GENERO (NOMBRE) VALUES ('Electronic dance');
INSERT INTO LISTAS_GENERO (NOMBRE) VALUES ('Dirty rap');
INSERT INTO LISTAS_GENERO (NOMBRE) VALUES ('Disco rock');
INSERT INTO LISTAS_GENERO (NOMBRE) VALUES ('Kraut-rock');
INSERT INTO LISTAS_GENERO (NOMBRE) VALUES ('Techno');
INSERT INTO LISTAS_GENERO ( NOMBRE) VALUES ('Reggaeton');
INSERT INTO LISTAS_GENERO ( NOMBRE) VALUES ('Disco');
INSERT INTO LISTAS_GENERO ( NOMBRE) VALUES ('Country rock');
INSERT INTO LISTAS_GENERO ( NOMBRE) VALUES ('Blugrass');
INSERT INTO LISTAS_GENERO ( NOMBRE) VALUES ('Pop Católico');



INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (1,1);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (2,2);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (3,3);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (4,4);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (4,5);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (5,6);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (5,7);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (5,8);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (6,9);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (6,10);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (7,4);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (8,11);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (8,9);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (8,14);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (9,12);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (9,13);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (9,4);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (10,12);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (11,3);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (12,15);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (13,16);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (14,16);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (15,16);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (16,20);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (17,4);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (18,3);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (19,17);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (20,3);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (21,18);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (22,19);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (23,20);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (24,16);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (25,19);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (26,16);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (27,21);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (28,22);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (29,16);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (30,23);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (30,22);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (31,6);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (31,11);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (31,7);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (32,3);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (32,19);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (33,20);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (33,16);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (33,3);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (34,3);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (35,22);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (36,22);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (36,5);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (37,16);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (38,16);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (39,24);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (40,3);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (41,25);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (41,26);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (42,27);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (42,16);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (43,4);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (43,28);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (44,29);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (44,30);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (44,16);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (44,17);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (45,3);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (45,22);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (45,6);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (46,27);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (46,3);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (47,22);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (47,4);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (48,3);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (49,27);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (50,23);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (50,3);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (51,4);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (51,17);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (51,25);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (51,3);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (52,6);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (53,4);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (53,5);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (53,3);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (54,4);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (55,25);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (55,19);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (55,17);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (56,4);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (57,22);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (57,3);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (58,1);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (58,8);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (58,31);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (59,16);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (59,17);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (60,32);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (60,3);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (61,3);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (61,21);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (61,16);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (62,25);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (62,26);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (62,27);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (62,2);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (63,3);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (64,32);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (65,2);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (65,9);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (66,3);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (66,5);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (66,9);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (66,33);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (67,33);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (67,5);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (68,5);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (69,3);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (70,2);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (71,3);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (72,3);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (73,3);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (74,3);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (74,25);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (75,16);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (76,34);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (77,16);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (77,34);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (78,2);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (79,19);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (80,30);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (81,16);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (82,16);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (83,16);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (84,16);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (85,16);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (85,21);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (86,16);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (87,16);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (88,16);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (89,19);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (90,19);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (91,6);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (92,20);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (93,16);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (94,16);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (94,34);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (94,21);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (95,2);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (96,16);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (97,16);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (97,2);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (98,16);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (99,16);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (100,3);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (100,32);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (101,32);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (101,4);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (102,32);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (103,32);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (104,32);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (105,32);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (105,3);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (106,32);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (107,32);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (108,32);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (109,3);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (109,26);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (109,17);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (109,25);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (110,12);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (110,34);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (110,3);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (111,12);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (111,34);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (112,12);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (113,12);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (114,12);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (115,12);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (116,12);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (117,35);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (117,12);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (118,12);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (119,12);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (119,35);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (120,12);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (121,12);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (122,12);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (123,12);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (124,12);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (125,12);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (126,12);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (127,12);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (128,12);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (129,12);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (130,33);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (131,3);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (132,28);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (133,3);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (134,3);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (135,36);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (136,13);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (136,4);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (137,3);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (138,3);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (139,3);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (139,32);


INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (1,1,20);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (2,1,19);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (3,1,18);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (4,1,17);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (5,1,16);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (6,1,15);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (7,1,14);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (8,1,13);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (9,1,12);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (10,1,11);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (11,1,10);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (12,1,9);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (13,1,8);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (14,1,7);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (15,1,6);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (16,1,5);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (17,1,4);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (19,1,3);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (18,1,2);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (20,1,1);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (21,2,13);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (22,2,20);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (23,2,19);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (16,2,18);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (24,2,17);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (25,2,16);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (26,2,15);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (27,2,14);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (28,2,12);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (29,2,11);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (30,2,10);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (31,2,9);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (32,2,8);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (33,2,7);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (34,2,6);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (35,2,5);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (36,2,4);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (37,2,3);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (38,2,2);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (39,2,1);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (40,3,20);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (41,3,19);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (42,3,18);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (43,3,17);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (44,3,16);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (45,3,15);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (46,3,14);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (47,3,13);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (48,3,11);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (49,3,12);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (50,3,1);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (51,3,2);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (52,3,3);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (53,3,4);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (54,3,5);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (55,3,6);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (56,3,7);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (57,3,8);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (58,3,9);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (59,3,10);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (60,4,20);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (53,4,19);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (61,4,18);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (62,4,17);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (63,4,16);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (64,4,15);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (45,4,14);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (65,4,13);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (66,4,12);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (67,4,11);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (68,4,1);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (69,4,2);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (70,4,3);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (71,4,4);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (20,4,5);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (72,4,6);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (40,4,7);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (57,4,8);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (73,4,9);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (74,4,10);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (75,5,11);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (76,5,12);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (77,5,13);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (78,5,14);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (79,5,15);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (80,5,16);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (81,5,17);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (82,5,18);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (83,5,19);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (84,5,20);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (85,5,10);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (86,5,9);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (87,5,8);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (88,5,7);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (89,5,6);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (90,5,5);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (33,5,4);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (91,5,3);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (92,5,2);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (39,5,1);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (38,6,1);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (35,6,2);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (87,6,3);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (39,6,4);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (93,6,5);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (94,6,6);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (95,6,7);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (34,6,8);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (32,6,9);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (37,6,10);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (96,6,11);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (21,6,12);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (29,6,13);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (36,6,14);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (33,6,15);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (83,6,16);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (97,6,17);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (98,6,18);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (99,6,19);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (91,6,20);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (100,7,1);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (101,7,2);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (102,7,3);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (103,7,4);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (104,7,5);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (105,7,6);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (106,7,7);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (107,7,8);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (108,7,9);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (109,7,10);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (110,8,20);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (111,8,19);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (112,8,18);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (113,8,17);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (114,8,16);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (115,8,15);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (116,8,14);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (117,8,13);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (118,8,12);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (119,8,11);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (120,8,10);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (121,8,9);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (122,8,8);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (123,8,7);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (124,8,6);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (125,8,5);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (126,8,4);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (127,8,3);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (128,8,2);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (129,8,1);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (130,9,1);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (131,9,2);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (132,9,3);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (133,9,4);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (134,9,5);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (135,9,6);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (136,9,7);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (137,9,8);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (138,9,9);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (139,9,10);

/*INSERCCIÓN 10 CANCIONES*/

INSERT INTO LISTAS_LISTA (NOMBRE,ANYO, FUENTE,AUTOR) VALUES ('Top 3 cancioines de Mary Jane',2025,'https://www.youtube.com/playlist?list=PL6DnBnDD0vV2ZaNsgpzgeF4z9N4Ax68zy','Mary Jane');
SELECT * FROM LISTAS_LISTA WHERE AUTOR='Mary Jane';

INSERT INTO LISTAS_PAIS(NOMBRE) VALUES ('Alemania');
SELECT * FROM LISTAS_PAIS WHERE NOMBRE='Alemania';

INSERT INTO LISTAS_PROVINCIA_ESTADO(NOMBRE, COD_PAIS) VALUES ('Berlín',16);
SELECT * FROM LISTAS_PROVINCIA_ESTADO WHERE COD_PAIS=16;

INSERT INTO LISTAS_CIUDAD(NOMBRE, PROVINCIA_ESTADO) VALUES('Berlín',50);
SELECT * FROM LISTAS_CIUDAD WHERE PROVINCIA_ESTADO=50;

INSERT INTO LISTAS_ARTISTA(NOMBREARTISTICO, COD_CIUDAD) VALUES('Mary Jane',84);
SELECT * FROM LISTAS_ARTISTA WHERE COD_CIUDAD=84;

INSERT INTO LISTAS_ARTISTAIND (COD, nombreReal, FNAC, FMUERTE) VALUES (120,'Mary Jane Watson',STR_TO_DATE('30-08-1984','%d-%m-%Y'),null);

INSERT INTO LISTAS_CANCION (TITULO, ANYO, COD_ARTISTA) VALUES ('VEN','2019',120);
INSERT INTO LISTAS_CANCION (TITULO, ANYO, COD_ARTISTA) VALUES ('Me comí el pastel','2019',120);
INSERT INTO LISTAS_CANCION (TITULO, ANYO, COD_ARTISTA) VALUES ('Panza cervezera','2019',120);
SELECT * FROM LISTAS_CANCION WHERE COD_ARTISTA=120;

INSERT INTO LISTAS_GENERO(NOMBRE) VALUES('Las canciones de Mary');
SELECT * FROM LISTAS_GENERO WHERE NOMBRE='Las canciones de Mary';

INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION, COD_GENERO) VALUES(140,37);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION, COD_GENERO) VALUES(141,37);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION, COD_GENERO) VALUES(142,37);




INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION, COD_LISTA, POSICION) VALUES(141,10,1);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION, COD_LISTA, POSICION) VALUES(140,10,2);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION, COD_LISTA, POSICION) VALUES(142,10,3);
SELECT * FROM LISTAS_POSICION_LISTA WHERE COD_LISTA=10;

