CREATE TABLE LISTAS_PAIS(
    ID INT PRIMARY KEY,    
    NOMBRE VARCHAR(50) UNIQUE KEY
);

CREATE TABLE LISTAS_ESTADO_PROVINCIA(
    NOMBRE VARCHAR(50),
    ID_PAIS INT,
    CONSTRAINT PK_ESTADO_PROV PRIMARY KEY (NOMBRE, ID_PAIS),
    CONSTRAINT FK_ESTADO_PAIS FOREIGN KEY (ID_PAIS) REFERENCES LISTAS_PAIS(ID) ON UPDATE CASCADE
);

CREATE TABLE LISTAS_CIUDAD(
    NOMBRE VARCHAR(50),
    NOM_ESTADO_PROV VARCHAR(50),
    ID_PAIS INT,
    CONSTRAINT PK_CIUDAD PRIMARY KEY (NOMBRE, ID_PAIS, NOM_ESTADO_PROV),
    CONSTRAINT FK_CIUDAD_ESTADO FOREIGN KEY (NOM_ESTADO_PROV, ID_PAIS) REFERENCES LISTAS_ESTADO_PROVINCIA(NOMBRE, ID_PAIS) ON UPDATE CASCADE
);

CREATE TABLE LISTAS_ARTISTA(
    COD INT PRIMARY KEY, 
    nombreArtistico VARCHAR(50) UNIQUE,
    NOM_CIUDAD VARCHAR(50),
    NOM_ESTADO_PROV VARCHAR(50),
    ID_PAIS INT,
    CONSTRAINT FK_ARTISTA FOREIGN KEY (NOM_ESTADO_PROV, ID_PAIS, NOM_CIUDAD) REFERENCES LISTAS_CIUDAD(NOM_ESTADO_PROV, ID_PAIS, NOMBRE) ON UPDATE CASCADE
);

CREATE TABLE LISTAS_GRUPO(
    COD INT PRIMARY KEY, 
    FCREACION DATE NOT NULL,
    FDISOLUCION DATE,
    FOREIGN KEY(COD) REFERENCES LISTAS_ARTISTA(COD) ON UPDATE CASCADE
);

CREATE TABLE LISTAS_ARTISTAIND(
    COD INT PRIMARY KEY, 
    nombreReal VARCHAR(100) UNIQUE NOT NULL,
    FNAC DATE NOT NULL,
    FMUERTE DATE,
    FOREIGN KEY(COD) REFERENCES LISTAS_ARTISTA(COD)
);

CREATE TABLE LISTAS_GENERO(
    COD INT PRIMARY KEY, 
    NOMBRE VARCHAR(50) UNIQUE
);

CREATE TABLE LISTAS_CANCION(
    COD INT PRIMARY KEY,
    TITULO VARCHAR(50) NOT NULL,
    ANYO NUMERIC(4,0),
    COD_ARTISTA INT NOT NULL,
    FOREIGN KEY(COD_ARTISTA) REFERENCES LISTAS_ARTISTA(COD)
);

CREATE TABLE LISTAS_GENERO_CANCION(
    COD_CANCION INT,
    COD_GENERO INT,
    PRIMARY KEY(COD_CANCION, COD_GENERO),
    FOREIGN KEY(COD_CANCION) REFERENCES LISTAS_CANCION(COD),
    FOREIGN KEY(COD_GENERO) REFERENCES LISTAS_GENERO(COD)
);

CREATE TABLE LISTAS_LISTA(
    COD INT PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    ANYO NUMERIC(4,0) NOT NULL,
    FUENTE VARCHAR(120),
    AUTOR VARCHAR(50)
);

CREATE TABLE LISTAS_POSICION_LISTA(
    COD_CANCION INT,
    COD_LISTA INT,
    POSICION NUMERIC(4),
    PRIMARY KEY(COD_CANCION, COD_LISTA, POSICION),
    FOREIGN KEY(COD_CANCION) REFERENCES LISTAS_CANCION(COD),
    FOREIGN KEY(COD_LISTA) REFERENCES LISTAS_LISTA(COD)
);

ALTER TABLE LISTAS_ARTISTAIND ADD CONSTRAINT MORIRDESPUES CHECK (FMUERTE > FNAC);
ALTER TABLE LISTAS_GRUPO ADD CONSTRAINT DISOLVERDESPUES CHECK (FDISOLUCION > FCREACION);
ALTER TABLE LISTAS_POSICION_LISTA ADD CONSTRAINT POSPOSITIVA CHECK (POSICION > 0);
ALTER TABLE LISTAS_LISTA ADD CONSTRAINT ANYOLISTA CHECK (ANYO > 0);

/*
DROP TABLE LISTAS_PAIS CASCADE;
DROP TABLE LISTAS_ESTADO_PROVINCIA CASCADE;
DROP TABLE LISTAS_GENERO CASCADE;
DROP TABLE LISTAS_CIUDAD CASCADE;
DROP TABLE LISTAS_CANCION CASCADE;
DROP TABLE LISTAS_LISTA CASCADE;
DROP TABLE LISTAS_ARTISTA CASCADE;
DROP TABLE LISTAS_GRUPO CASCADE;
DROP TABLE LISTAS_ARTISTAIND CASCADE;
DROP TABLE LISTAS_GENERO_CANCION CASCADE;
DROP TABLE LISTAS_POSICION_LISTA CASCADE;
*/


-- Creamos la secuencia que pertenece al DDL solo para ORACLE.
-- DROP SEQUENCE secuencia_en_lista;
/*CREATE SEQUENCE secuencia_en_lista START WITH 1 INCREMENT BY 1 MAXVALUE 999;*/



INSERT INTO LISTAS_PAIS VALUES (1,1);
INSERT INTO LISTAS_PAIS VALUES (2,'Senegal');
INSERT INTO LISTAS_PAIS VALUES (3,'Mongolia');
INSERT INTO LISTAS_PAIS VALUES (4,'Estados Unidos');
INSERT INTO LISTAS_PAIS VALUES (5,'Reino Unido');
INSERT INTO LISTAS_PAIS VALUES (6,'Suecia');
INSERT INTO LISTAS_PAIS VALUES (7,'Colombia');
INSERT INTO LISTAS_PAIS VALUES (8,'Trinidad y Tobago');
INSERT INTO LISTAS_PAIS VALUES (9,'Italia');
INSERT INTO LISTAS_PAIS VALUES (10,'Panamá');
INSERT INTO LISTAS_PAIS VALUES (11,'Australia');
INSERT INTO LISTAS_PAIS VALUES (12,'Canadá');
INSERT INTO LISTAS_PAIS VALUES (13,'Noruega');
INSERT INTO LISTAS_PAIS VALUES (14,'Francia');
INSERT INTO LISTAS_PAIS VALUES (15,'Nueva Zelanda');




INSERT INTO LISTAS_ESTADO_PROVINCIA (NOMBRE,ID_PAIS) VALUES ('Gran Londres',5);
INSERT INTO LISTAS_ESTADO_PROVINCIA (NOMBRE,ID_PAIS) VALUES ('Nueva Jersey',5);
INSERT INTO LISTAS_ESTADO_PROVINCIA (NOMBRE,ID_PAIS) VALUES ('Georgia',4);
INSERT INTO LISTAS_ESTADO_PROVINCIA (NOMBRE,ID_PAIS) VALUES ('Oxfordshire',5);
INSERT INTO LISTAS_ESTADO_PROVINCIA (NOMBRE,ID_PAIS) VALUES ('Pensilvania',4);
INSERT INTO LISTAS_ESTADO_PROVINCIA (NOMBRE,ID_PAIS) VALUES ('Gran Machester',5);
INSERT INTO LISTAS_ESTADO_PROVINCIA (NOMBRE,ID_PAIS) VALUES ('Nueva York',4);
INSERT INTO LISTAS_ESTADO_PROVINCIA (NOMBRE,ID_PAIS) VALUES ('Misisipi',4);
INSERT INTO LISTAS_ESTADO_PROVINCIA (NOMBRE,ID_PAIS) VALUES ('Misuri',4);
INSERT INTO LISTAS_ESTADO_PROVINCIA (NOMBRE,ID_PAIS) VALUES ('Indiana',4);
INSERT INTO LISTAS_ESTADO_PROVINCIA (NOMBRE,ID_PAIS) VALUES ('Merseyside',5);
INSERT INTO LISTAS_ESTADO_PROVINCIA (NOMBRE,ID_PAIS) VALUES ('Minesota',4);
INSERT INTO LISTAS_ESTADO_PROVINCIA (NOMBRE,ID_PAIS) VALUES ('Washington',4);
INSERT INTO LISTAS_ESTADO_PROVINCIA (NOMBRE,ID_PAIS) VALUES ('California',4);
INSERT INTO LISTAS_ESTADO_PROVINCIA (NOMBRE,ID_PAIS) VALUES ('Washington D. C.',4);
INSERT INTO LISTAS_ESTADO_PROVINCIA (NOMBRE,ID_PAIS) VALUES ('Estocolmo',6);
INSERT INTO LISTAS_ESTADO_PROVINCIA (NOMBRE,ID_PAIS) VALUES ('Virginia',4);
INSERT INTO LISTAS_ESTADO_PROVINCIA (NOMBRE,ID_PAIS) VALUES ('Texas',4);
INSERT INTO LISTAS_ESTADO_PROVINCIA (NOMBRE,ID_PAIS) VALUES ('Míchigan',4);
INSERT INTO LISTAS_ESTADO_PROVINCIA (NOMBRE,ID_PAIS) VALUES ('Auckland',15);
INSERT INTO LISTAS_ESTADO_PROVINCIA (NOMBRE,ID_PAIS) VALUES ('Puerto Rico',4);
INSERT INTO LISTAS_ESTADO_PROVINCIA (NOMBRE,ID_PAIS) VALUES ('West Yorkshire',5);
INSERT INTO LISTAS_ESTADO_PROVINCIA (NOMBRE,ID_PAIS) VALUES ('Ontario',12);
INSERT INTO LISTAS_ESTADO_PROVINCIA (NOMBRE,ID_PAIS) VALUES ('Atlántico',7);
INSERT INTO LISTAS_ESTADO_PROVINCIA (NOMBRE,ID_PAIS) VALUES ('Oslo',13);
INSERT INTO LISTAS_ESTADO_PROVINCIA (NOMBRE,ID_PAIS) VALUES ('Hawái',4);
INSERT INTO LISTAS_ESTADO_PROVINCIA (NOMBRE,ID_PAIS) VALUES ('Isla de Francia',14);
INSERT INTO LISTAS_ESTADO_PROVINCIA (NOMBRE,ID_PAIS) VALUES ('Florida',4);
INSERT INTO LISTAS_ESTADO_PROVINCIA (NOMBRE,ID_PAIS) VALUES ('Irlanda del Norte',5);
INSERT INTO LISTAS_ESTADO_PROVINCIA (NOMBRE,ID_PAIS) VALUES ('Oregón',4);
INSERT INTO LISTAS_ESTADO_PROVINCIA (NOMBRE,ID_PAIS) VALUES ('Antioquia',7);
INSERT INTO LISTAS_ESTADO_PROVINCIA (NOMBRE,ID_PAIS) VALUES ('Piamonte',9);
INSERT INTO LISTAS_ESTADO_PROVINCIA (NOMBRE,ID_PAIS) VALUES ('Granada',1);
INSERT INTO LISTAS_ESTADO_PROVINCIA (NOMBRE,ID_PAIS) VALUES ('Panamá',10);
INSERT INTO LISTAS_ESTADO_PROVINCIA (NOMBRE,ID_PAIS) VALUES ('Victoria',11);
INSERT INTO LISTAS_ESTADO_PROVINCIA (NOMBRE,ID_PAIS) VALUES ('Kentucky',4);
INSERT INTO LISTAS_ESTADO_PROVINCIA (NOMBRE,ID_PAIS) VALUES ('Tennessee',4);
INSERT INTO LISTAS_ESTADO_PROVINCIA (NOMBRE,ID_PAIS) VALUES ('Alabama',4);
INSERT INTO LISTAS_ESTADO_PROVINCIA (NOMBRE,ID_PAIS) VALUES ('Arkansas',4);
INSERT INTO LISTAS_ESTADO_PROVINCIA (NOMBRE,ID_PAIS) VALUES ('Madrid',1);
INSERT INTO LISTAS_ESTADO_PROVINCIA (NOMBRE,ID_PAIS) VALUES ('Tarragona',1);
INSERT INTO LISTAS_ESTADO_PROVINCIA (NOMBRE,ID_PAIS) VALUES ('Valencia',1);
INSERT INTO LISTAS_ESTADO_PROVINCIA (NOMBRE,ID_PAIS) VALUES ('Dundgovi',3);
INSERT INTO LISTAS_ESTADO_PROVINCIA (NOMBRE,ID_PAIS) VALUES ('Sevilla',1);
INSERT INTO LISTAS_ESTADO_PROVINCIA (NOMBRE,ID_PAIS) VALUES ('Girona',1);
INSERT INTO LISTAS_ESTADO_PROVINCIA (NOMBRE,ID_PAIS) VALUES ('Dakar',2);
INSERT INTO LISTAS_ESTADO_PROVINCIA (NOMBRE,ID_PAIS) VALUES ('Las Palmas de Gran Canaria', 1);
INSERT INTO LISTAS_ESTADO_PROVINCIA (NOMBRE,ID_PAIS) VALUES ('Barcelona',1);
INSERT INTO LISTAS_ESTADO_PROVINCIA (NOMBRE,ID_PAIS) VALUES ('Escocia',5);
INSERT INTO LISTAS_ESTADO_PROVINCIA (NOMBRE,ID_PAIS) VALUES ('Latina',9);


	
INSERT INTO LISTAS_CIUDAD (NOMBRE,NOM_ESTADO_PROV,ID_PAIS) VALUES ('Bexleyheath','Gran Londres',5);
INSERT INTO LISTAS_CIUDAD (NOMBRE,NOM_ESTADO_PROV,ID_PAIS) VALUES ('Basildon','Nueva Jersey',5);
INSERT INTO LISTAS_CIUDAD (NOMBRE,NOM_ESTADO_PROV,ID_PAIS) VALUES ('Memphis','Tennessee',4);
INSERT INTO LISTAS_CIUDAD (NOMBRE,NOM_ESTADO_PROV,ID_PAIS) VALUES ('Atlanta','Oxfordshire',5);
INSERT INTO LISTAS_CIUDAD (NOMBRE,NOM_ESTADO_PROV,ID_PAIS) VALUES ('Abingdon','Oxfordshire',5);
INSERT INTO LISTAS_CIUDAD (NOMBRE,NOM_ESTADO_PROV,ID_PAIS) VALUES ('Athens','Oxfordshire',5);
INSERT INTO LISTAS_CIUDAD (NOMBRE,NOM_ESTADO_PROV,ID_PAIS) VALUES ('Londres','Gran Londres',5);
INSERT INTO LISTAS_CIUDAD (NOMBRE,NOM_ESTADO_PROV,ID_PAIS) VALUES ('Reading','Pensilvania',4);
INSERT INTO LISTAS_CIUDAD (NOMBRE,NOM_ESTADO_PROV,ID_PAIS) VALUES ('Manchester','Gran Machester',5);
INSERT INTO LISTAS_CIUDAD (NOMBRE,NOM_ESTADO_PROV,ID_PAIS) VALUES ('Queens','Nueva York',4);
INSERT INTO LISTAS_CIUDAD (NOMBRE,NOM_ESTADO_PROV,ID_PAIS) VALUES ('Tupelo','Misisipi',4);
INSERT INTO LISTAS_CIUDAD (NOMBRE,NOM_ESTADO_PROV,ID_PAIS) VALUES ('San Luis','Misuri',4);
INSERT INTO LISTAS_CIUDAD (NOMBRE,NOM_ESTADO_PROV,ID_PAIS) VALUES ('Gary','Indiana',4);
INSERT INTO LISTAS_CIUDAD (NOMBRE,NOM_ESTADO_PROV,ID_PAIS) VALUES ('McComb','Misisipi',4);
INSERT INTO LISTAS_CIUDAD (NOMBRE,NOM_ESTADO_PROV,ID_PAIS) VALUES ('Liverpool','Merseyside',5);
INSERT INTO LISTAS_CIUDAD (NOMBRE,NOM_ESTADO_PROV,ID_PAIS) VALUES ('Duluth','Minesota',4);
INSERT INTO LISTAS_CIUDAD (NOMBRE,NOM_ESTADO_PROV,ID_PAIS) VALUES ('Clarksdale','Misisipi',4);
INSERT INTO LISTAS_CIUDAD (NOMBRE,NOM_ESTADO_PROV,ID_PAIS) VALUES ('Albany','Oxfordshire',5);
INSERT INTO LISTAS_CIUDAD (NOMBRE,NOM_ESTADO_PROV,ID_PAIS) VALUES ('Aberdeen','Washington',4);
INSERT INTO LISTAS_CIUDAD (NOMBRE,NOM_ESTADO_PROV,ID_PAIS) VALUES ('Hawthorne','California',4);
INSERT INTO LISTAS_CIUDAD (NOMBRE,NOM_ESTADO_PROV,ID_PAIS) VALUES ('Washington D. C.','Washington D. C.',4);
INSERT INTO LISTAS_CIUDAD (NOMBRE,NOM_ESTADO_PROV,ID_PAIS) VALUES ('Enfield','Gran Londres',5);
INSERT INTO LISTAS_CIUDAD (NOMBRE,NOM_ESTADO_PROV,ID_PAIS) VALUES ('Estocolmo','Estocolmo',6);
INSERT INTO LISTAS_CIUDAD (NOMBRE,NOM_ESTADO_PROV,ID_PAIS) VALUES ('Brixton','Gran Londres',5);
INSERT INTO LISTAS_CIUDAD (NOMBRE,NOM_ESTADO_PROV,ID_PAIS) VALUES ('Portsmouth','Virginia',4);
INSERT INTO LISTAS_CIUDAD (NOMBRE,NOM_ESTADO_PROV,ID_PAIS) VALUES ('Brooklyn','Nueva York',4);
INSERT INTO LISTAS_CIUDAD (NOMBRE,NOM_ESTADO_PROV,ID_PAIS) VALUES ('Compton','California',4);
INSERT INTO LISTAS_CIUDAD (NOMBRE,NOM_ESTADO_PROV,ID_PAIS) VALUES ('Fort Worth','Texas',4);
INSERT INTO LISTAS_CIUDAD (NOMBRE,NOM_ESTADO_PROV,ID_PAIS) VALUES ('Houston','Texas',4);
INSERT INTO LISTAS_CIUDAD (NOMBRE,NOM_ESTADO_PROV,ID_PAIS) VALUES ('Hounslow','Gran Londres',5);
INSERT INTO LISTAS_CIUDAD (NOMBRE,NOM_ESTADO_PROV,ID_PAIS) VALUES ('Detroit','Míchigan',4);
INSERT INTO LISTAS_CIUDAD (NOMBRE,NOM_ESTADO_PROV,ID_PAIS) VALUES ('Nueva York','Nueva York',4);
INSERT INTO LISTAS_CIUDAD (NOMBRE,NOM_ESTADO_PROV,ID_PAIS) VALUES ('Auckland','Auckland',15);
INSERT INTO LISTAS_CIUDAD (NOMBRE,NOM_ESTADO_PROV,ID_PAIS) VALUES ('San Juan','Puerto Rico',4);
INSERT INTO LISTAS_CIUDAD (NOMBRE,NOM_ESTADO_PROV,ID_PAIS) VALUES ('Halifax','West Yorkshire',5);
INSERT INTO LISTAS_CIUDAD (NOMBRE,NOM_ESTADO_PROV,ID_PAIS) VALUES ('Santa Bárbara','California',4);
INSERT INTO LISTAS_CIUDAD (NOMBRE,NOM_ESTADO_PROV,ID_PAIS) VALUES ('London','Ontario',12);
INSERT INTO LISTAS_CIUDAD (NOMBRE,NOM_ESTADO_PROV,ID_PAIS) VALUES ('Barranquilla','Atlántico',7);
INSERT INTO LISTAS_CIUDAD (NOMBRE,NOM_ESTADO_PROV,ID_PAIS) VALUES ('Oslo','Oslo',13);
INSERT INTO LISTAS_CIUDAD (NOMBRE,NOM_ESTADO_PROV,ID_PAIS) VALUES ('Honolulú','Hawái',4);
INSERT INTO LISTAS_CIUDAD (NOMBRE,NOM_ESTADO_PROV,ID_PAIS) VALUES ('París','Isla de Francia',14);
INSERT INTO LISTAS_CIUDAD (NOMBRE,NOM_ESTADO_PROV,ID_PAIS) VALUES ('Bay City','Míchigan',4);
INSERT INTO LISTAS_CIUDAD (NOMBRE,NOM_ESTADO_PROV,ID_PAIS) VALUES ('Mineápolis','Minesota',4);
INSERT INTO LISTAS_CIUDAD (NOMBRE,NOM_ESTADO_PROV,ID_PAIS) VALUES ('Newark','Nueva Jersey',5);
INSERT INTO LISTAS_CIUDAD (NOMBRE,NOM_ESTADO_PROV,ID_PAIS) VALUES ('Orlando','Florida',4);
INSERT INTO LISTAS_CIUDAD (NOMBRE,NOM_ESTADO_PROV,ID_PAIS) VALUES ('Los Ángeles','California',4);
INSERT INTO LISTAS_CIUDAD (NOMBRE,NOM_ESTADO_PROV,ID_PAIS) VALUES ('Belfast','Washington D. C.',4);
INSERT INTO LISTAS_CIUDAD (NOMBRE,NOM_ESTADO_PROV,ID_PAIS) VALUES ('Malibú','California',4);
INSERT INTO LISTAS_CIUDAD (NOMBRE,NOM_ESTADO_PROV,ID_PAIS) VALUES ('Long Branch','Nueva Jersey',5);
INSERT INTO LISTAS_CIUDAD (NOMBRE,NOM_ESTADO_PROV,ID_PAIS) VALUES ('Toronto','Ontario',12);
INSERT INTO LISTAS_CIUDAD (NOMBRE,NOM_ESTADO_PROV,ID_PAIS) VALUES ('Portland','Oregón',4);
INSERT INTO LISTAS_CIUDAD (NOMBRE,NOM_ESTADO_PROV,ID_PAIS) VALUES ('New Rochelle','Nueva York',4);
INSERT INTO LISTAS_CIUDAD (NOMBRE,NOM_ESTADO_PROV,ID_PAIS) VALUES ('Medellín','Antioquia',7);
INSERT INTO LISTAS_CIUDAD (NOMBRE,NOM_ESTADO_PROV,ID_PAIS) VALUES ('Turín','Piamonte',9);
INSERT INTO LISTAS_CIUDAD (NOMBRE,NOM_ESTADO_PROV,ID_PAIS) VALUES ('Salinas','Puerto Rico',4);
INSERT INTO LISTAS_CIUDAD (NOMBRE,NOM_ESTADO_PROV,ID_PAIS) VALUES ('Ítrabo','Granada',1);
INSERT INTO LISTAS_CIUDAD (NOMBRE,NOM_ESTADO_PROV,ID_PAIS) VALUES ('Almirante Sur','Puerto Rico',4);
INSERT INTO LISTAS_CIUDAD (NOMBRE, NOM_ESTADO_PROV, ID_PAIS) VALUES ('Río Abajo', 'Panamá', 10);
INSERT INTO LISTAS_CIUDAD (NOMBRE,NOM_ESTADO_PROV,ID_PAIS) VALUES ('Mount Martha','Victoria',11);
INSERT INTO LISTAS_CIUDAD (NOMBRE,NOM_ESTADO_PROV,ID_PAIS) VALUES ('Butcker Hollow','Kentucky',4);
INSERT INTO LISTAS_CIUDAD (NOMBRE,NOM_ESTADO_PROV,ID_PAIS) VALUES ('Poteet','Texas',4);
INSERT INTO LISTAS_CIUDAD (NOMBRE,NOM_ESTADO_PROV,ID_PAIS) VALUES ('Kosse','Texas',4);
INSERT INTO LISTAS_CIUDAD (NOMBRE,NOM_ESTADO_PROV,ID_PAIS) VALUES ('Nashville','Tennessee',4);
INSERT INTO LISTAS_CIUDAD (NOMBRE,NOM_ESTADO_PROV,ID_PAIS) VALUES ('Mount Olive','Alabama',4);
INSERT INTO LISTAS_CIUDAD (NOMBRE,NOM_ESTADO_PROV,ID_PAIS) VALUES ('Rosine','Kentucky',4);
INSERT INTO LISTAS_CIUDAD (NOMBRE,NOM_ESTADO_PROV,ID_PAIS) VALUES ('Sherman','Texas',4);
INSERT INTO LISTAS_CIUDAD (NOMBRE,NOM_ESTADO_PROV,ID_PAIS) VALUES ('Dickenson County','Virginia',4);
INSERT INTO LISTAS_CIUDAD (NOMBRE,NOM_ESTADO_PROV,ID_PAIS) VALUES ('Littlefield','Texas',4);
INSERT INTO LISTAS_CIUDAD (NOMBRE,NOM_ESTADO_PROV,ID_PAIS) VALUES ('Sevierville','Tennessee',4);
INSERT INTO LISTAS_CIUDAD (NOMBRE,NOM_ESTADO_PROV,ID_PAIS) VALUES ('Bakersfield','California',4);
INSERT INTO LISTAS_CIUDAD (NOMBRE,NOM_ESTADO_PROV,ID_PAIS) VALUES ('Itawamba','Misisipi',4);
INSERT INTO LISTAS_CIUDAD (NOMBRE,NOM_ESTADO_PROV,ID_PAIS) VALUES ('Vidor','Texas',4);
INSERT INTO LISTAS_CIUDAD (NOMBRE,NOM_ESTADO_PROV,ID_PAIS) VALUES ('Winchester','Virginia',4);
INSERT INTO LISTAS_CIUDAD (NOMBRE,NOM_ESTADO_PROV,ID_PAIS) VALUES ('Kingsland','Arkansas',4);
INSERT INTO LISTAS_CIUDAD (NOMBRE,NOM_ESTADO_PROV,ID_PAIS) VALUES ('Madrid','Madrid',1);
INSERT INTO LISTAS_CIUDAD (NOMBRE,NOM_ESTADO_PROV,ID_PAIS) VALUES ('Tortosa','Tarragona',1);
INSERT INTO LISTAS_CIUDAD (NOMBRE,NOM_ESTADO_PROV,ID_PAIS) VALUES ('Sagunto','Valencia',1);
INSERT INTO LISTAS_CIUDAD (NOMBRE,NOM_ESTADO_PROV,ID_PAIS) VALUES ('Mandalgobi','Dundgovi',3);
INSERT INTO LISTAS_CIUDAD (NOMBRE,NOM_ESTADO_PROV,ID_PAIS) VALUES ('Sevilla','Sevilla',1);
INSERT INTO LISTAS_CIUDAD (NOMBRE,NOM_ESTADO_PROV,ID_PAIS) VALUES ('Sant Jordi Desvalls','Girona',1);
INSERT INTO LISTAS_CIUDAD (NOMBRE,NOM_ESTADO_PROV,ID_PAIS) VALUES ('Dakar','Dakar',2);
INSERT INTO LISTAS_CIUDAD (NOMBRE,NOM_ESTADO_PROV,ID_PAIS) VALUES ('Gran Canaria','Las Palmas de Gran Canaria', 1);
INSERT INTO LISTAS_CIUDAD (NOMBRE,NOM_ESTADO_PROV,ID_PAIS) VALUES ('Barcelona','Barcelona',1);
INSERT INTO LISTAS_CIUDAD (NOMBRE,NOM_ESTADO_PROV,ID_PAIS) VALUES ('Agoura Hills','California',4);
INSERT INTO LISTAS_CIUDAD (NOMBRE,NOM_ESTADO_PROV,ID_PAIS) VALUES ('Clydebank','Escocia',5);
INSERT INTO LISTAS_CIUDAD (NOMBRE,NOM_ESTADO_PROV,ID_PAIS) VALUES ('Latina','Latina',9);



INSERT INTO LISTAS_ARTISTA (COD,nombreArtistico,NOM_CIUDAD,NOM_ESTADO_PROV, ID_PAIS) VALUES (1,'Kate Bush','Bexleyheath','Gran Londres',5);
INSERT INTO LISTAS_ARTISTA (COD,nombreArtistico,NOM_CIUDAD,NOM_ESTADO_PROV, ID_PAIS) VALUES (2,'Depeche Mode','Basildon','Nueva Jersey',5);
INSERT INTO LISTAS_ARTISTA (COD,nombreArtistico,NOM_CIUDAD,NOM_ESTADO_PROV, ID_PAIS) VALUES (3,'The Box Tops','Memphis','Tennessee',4);
INSERT INTO LISTAS_ARTISTA (COD,nombreArtistico,NOM_CIUDAD,NOM_ESTADO_PROV, ID_PAIS) VALUES (4,'OutKast','Atlanta','Oxfordshire',5);
INSERT INTO LISTAS_ARTISTA (COD,nombreArtistico,NOM_CIUDAD,NOM_ESTADO_PROV, ID_PAIS) VALUES (5,'Radiohead','Abingdon','Oxfordshire',5);
INSERT INTO LISTAS_ARTISTA (COD,nombreArtistico,NOM_CIUDAD,NOM_ESTADO_PROV, ID_PAIS) VALUES (6,'The B-52’s','Athens','Oxfordshire',5);
INSERT INTO LISTAS_ARTISTA (COD,nombreArtistico,NOM_CIUDAD,NOM_ESTADO_PROV, ID_PAIS) VALUES (7,'Kanye West','Atlanta','Oxfordshire',5);
INSERT INTO LISTAS_ARTISTA (COD,nombreArtistico,NOM_CIUDAD,NOM_ESTADO_PROV, ID_PAIS) VALUES (8,'The Clash','Athens','Oxfordshire',5);
INSERT INTO LISTAS_ARTISTA (COD,nombreArtistico,NOM_CIUDAD,NOM_ESTADO_PROV, ID_PAIS) VALUES (9,'Lil Nas X','Atlanta','Oxfordshire',5);
INSERT INTO LISTAS_ARTISTA (COD,nombreArtistico,NOM_CIUDAD,NOM_ESTADO_PROV, ID_PAIS) VALUES (10,'Taylor Swift','Reading','Pensilvania',4);
INSERT INTO LISTAS_ARTISTA (COD,nombreArtistico,NOM_CIUDAD,NOM_ESTADO_PROV, ID_PAIS) VALUES (11,'The Smiths','Manchester','Gran Machester',5);
INSERT INTO LISTAS_ARTISTA (COD,nombreArtistico,NOM_CIUDAD,NOM_ESTADO_PROV, ID_PAIS) VALUES (12,'Ramones','Queens','Nueva York',4);
INSERT INTO LISTAS_ARTISTA (COD,nombreArtistico,NOM_CIUDAD,NOM_ESTADO_PROV, ID_PAIS) VALUES (13,'Elvis Presley','Tupelo','Misisipi',4);
INSERT INTO LISTAS_ARTISTA (COD,nombreArtistico,NOM_CIUDAD,NOM_ESTADO_PROV, ID_PAIS) VALUES (14,'Led Zeppelin','Athens','Oxfordshire',5);
INSERT INTO LISTAS_ARTISTA (COD,nombreArtistico,NOM_CIUDAD,NOM_ESTADO_PROV, ID_PAIS) VALUES (15,'R.E.M','Athens','Oxfordshire',5);
INSERT INTO LISTAS_ARTISTA (COD,nombreArtistico,NOM_CIUDAD,NOM_ESTADO_PROV, ID_PAIS) VALUES (16,'Chuck Berry','San Luis','Misuri',4);
INSERT INTO LISTAS_ARTISTA (COD,nombreArtistico,NOM_CIUDAD,NOM_ESTADO_PROV, ID_PAIS) VALUES (17,'Run-DMC','Queens','Nueva York',4);
INSERT INTO LISTAS_ARTISTA (COD,nombreArtistico,NOM_CIUDAD,NOM_ESTADO_PROV, ID_PAIS) VALUES (18,'The Jackson 5','Gary','Indiana',4);
INSERT INTO LISTAS_ARTISTA (COD,nombreArtistico,NOM_CIUDAD,NOM_ESTADO_PROV, ID_PAIS) VALUES (19,'The Sex Pistols','Athens','Oxfordshire',5);
INSERT INTO LISTAS_ARTISTA (COD,nombreArtistico,NOM_CIUDAD,NOM_ESTADO_PROV, ID_PAIS) VALUES (20,'Britney Spears','McComb','Misisipi',4);
INSERT INTO LISTAS_ARTISTA (COD,nombreArtistico,NOM_CIUDAD,NOM_ESTADO_PROV, ID_PAIS) VALUES (21,'The Beatles','Liverpool','Merseyside',5);
INSERT INTO LISTAS_ARTISTA (COD,nombreArtistico,NOM_CIUDAD,NOM_ESTADO_PROV, ID_PAIS) VALUES (22,'The Jimi Hendrix Experience','Athens','Oxfordshire',5);
INSERT INTO LISTAS_ARTISTA (COD,nombreArtistico,NOM_CIUDAD,NOM_ESTADO_PROV, ID_PAIS) VALUES (24,'Bob Dylan','Duluth','Minesota',4);
INSERT INTO LISTAS_ARTISTA (COD,nombreArtistico,NOM_CIUDAD,NOM_ESTADO_PROV, ID_PAIS) VALUES (25,'Sam Cooke','Clarksdale','Misisipi',4);
INSERT INTO LISTAS_ARTISTA (COD,nombreArtistico,NOM_CIUDAD,NOM_ESTADO_PROV, ID_PAIS) VALUES (26,'The Who','Athens','Oxfordshire',5);
INSERT INTO LISTAS_ARTISTA (COD,nombreArtistico,NOM_CIUDAD,NOM_ESTADO_PROV, ID_PAIS) VALUES (27,'Ray Charles','Albany','Oxfordshire',5);
INSERT INTO LISTAS_ARTISTA (COD,nombreArtistico,NOM_CIUDAD,NOM_ESTADO_PROV, ID_PAIS) VALUES (28,'Nirvana','Aberdeen','Washington',4);
INSERT INTO LISTAS_ARTISTA (COD,nombreArtistico,NOM_CIUDAD,NOM_ESTADO_PROV, ID_PAIS) VALUES (29,'The Beach Boys','Hawthorne','California',4);
INSERT INTO LISTAS_ARTISTA (COD,nombreArtistico,NOM_CIUDAD,NOM_ESTADO_PROV, ID_PAIS) VALUES (30,'Aretha Franklin','Memphis','Tennessee',4);
INSERT INTO LISTAS_ARTISTA (COD,nombreArtistico,NOM_CIUDAD,NOM_ESTADO_PROV, ID_PAIS) VALUES (31,'Marvin Gaye','Washington D. C.','Washington D. C.',4);
INSERT INTO LISTAS_ARTISTA (COD,nombreArtistico,NOM_CIUDAD,NOM_ESTADO_PROV, ID_PAIS) VALUES (32,'John Lennon','Athens','Oxfordshire',5);
INSERT INTO LISTAS_ARTISTA (COD,nombreArtistico,NOM_CIUDAD,NOM_ESTADO_PROV, ID_PAIS) VALUES (33,'The Rolling Stones','Athens','Oxfordshire',5);
INSERT INTO LISTAS_ARTISTA (COD,nombreArtistico,NOM_CIUDAD,NOM_ESTADO_PROV, ID_PAIS) VALUES (34,'Amy Winehouse','Enfield','Gran Londres',5);
INSERT INTO LISTAS_ARTISTA (COD,nombreArtistico,NOM_CIUDAD,NOM_ESTADO_PROV, ID_PAIS) VALUES (35,'Robyn','Estocolmo','Estocolmo',6);
INSERT INTO LISTAS_ARTISTA (COD,nombreArtistico,NOM_CIUDAD,NOM_ESTADO_PROV, ID_PAIS) VALUES (36,'David Bowie','Brixton','Gran Londres',5);
INSERT INTO LISTAS_ARTISTA (COD,nombreArtistico,NOM_CIUDAD,NOM_ESTADO_PROV, ID_PAIS) VALUES (37,'Missy Elliot','Portsmouth','Virginia',4);
INSERT INTO LISTAS_ARTISTA (COD,nombreArtistico,NOM_CIUDAD,NOM_ESTADO_PROV, ID_PAIS) VALUES (38,'LCD Soundsystem','Brooklyn','Nueva York',4);
INSERT INTO LISTAS_ARTISTA (COD,nombreArtistico,NOM_CIUDAD,NOM_ESTADO_PROV, ID_PAIS) VALUES (39,'Gnarls Barkley','Atlanta','Oxfordshire',5);
INSERT INTO LISTAS_ARTISTA (COD,nombreArtistico,NOM_CIUDAD,NOM_ESTADO_PROV, ID_PAIS) VALUES (40,'Kendrick Lamar','Compton','California',4);
INSERT INTO LISTAS_ARTISTA (COD,nombreArtistico,NOM_CIUDAD,NOM_ESTADO_PROV, ID_PAIS) VALUES (41,'Kelly Clarkson','Fort Worth','Texas',4);
INSERT INTO LISTAS_ARTISTA (COD,nombreArtistico,NOM_CIUDAD,NOM_ESTADO_PROV, ID_PAIS) VALUES (42,'Beyoncé','Houston','Texas',4);
INSERT INTO LISTAS_ARTISTA (COD,nombreArtistico,NOM_CIUDAD,NOM_ESTADO_PROV, ID_PAIS) VALUES (43,'M.I.A.','Hounslow','Gran Londres',5);
INSERT INTO LISTAS_ARTISTA (COD,nombreArtistico,NOM_CIUDAD,NOM_ESTADO_PROV, ID_PAIS) VALUES (44,'The White Stripes','Detroit','Míchigan',4);
INSERT INTO LISTAS_ARTISTA (COD,nombreArtistico,NOM_CIUDAD,NOM_ESTADO_PROV, ID_PAIS) VALUES (45,'Jay-Z','Brooklyn','Nueva York',4);
INSERT INTO LISTAS_ARTISTA (COD,nombreArtistico,NOM_CIUDAD,NOM_ESTADO_PROV, ID_PAIS) VALUES (46,'Yeah Yeah Yeahs','Nueva York','Nueva York',4);
INSERT INTO LISTAS_ARTISTA (COD,nombreArtistico,NOM_CIUDAD,NOM_ESTADO_PROV, ID_PAIS) VALUES (47,'Adele','Londres','Gran Londres',5);
INSERT INTO LISTAS_ARTISTA (COD,nombreArtistico,NOM_CIUDAD,NOM_ESTADO_PROV, ID_PAIS) VALUES (48,'Lorde','Auckland','Auckland',15);
INSERT INTO LISTAS_ARTISTA (COD,nombreArtistico,NOM_CIUDAD,NOM_ESTADO_PROV, ID_PAIS) VALUES (49,'The Strokes','Nueva York','Nueva York',4);
INSERT INTO LISTAS_ARTISTA (COD,nombreArtistico,NOM_CIUDAD,NOM_ESTADO_PROV, ID_PAIS) VALUES (50,'Luis Fonsi','San Juan','Puerto Rico',4);
INSERT INTO LISTAS_ARTISTA (COD,nombreArtistico,NOM_CIUDAD,NOM_ESTADO_PROV, ID_PAIS) VALUES (51,'Ed Sheeran','Halifax','West Yorkshire',5);
INSERT INTO LISTAS_ARTISTA (COD,nombreArtistico,NOM_CIUDAD,NOM_ESTADO_PROV, ID_PAIS) VALUES (52,'Katy Perry','Santa Bárbara','California',4);
INSERT INTO LISTAS_ARTISTA (COD,nombreArtistico,NOM_CIUDAD,NOM_ESTADO_PROV, ID_PAIS) VALUES (53,'Justin Bieber','London','Ontario',12);
INSERT INTO LISTAS_ARTISTA (COD,nombreArtistico,NOM_CIUDAD,NOM_ESTADO_PROV, ID_PAIS) VALUES (54,'Shakira','Barranquilla','Atlántico',7);
INSERT INTO LISTAS_ARTISTA (COD,nombreArtistico,NOM_CIUDAD,NOM_ESTADO_PROV, ID_PAIS) VALUES (55,'A-ha','Oslo','Oslo',13);
INSERT INTO LISTAS_ARTISTA (COD,nombreArtistico,NOM_CIUDAD,NOM_ESTADO_PROV, ID_PAIS) VALUES (56,'Bruno Mars','Honolulú','Hawái',4);
INSERT INTO LISTAS_ARTISTA (COD,nombreArtistico,NOM_CIUDAD,NOM_ESTADO_PROV, ID_PAIS) VALUES (57,'Daft Punk','París','Isla de Francia',14);
INSERT INTO LISTAS_ARTISTA (COD,nombreArtistico,NOM_CIUDAD,NOM_ESTADO_PROV, ID_PAIS) VALUES (58,'Michael Jackson','Gary','Indiana',4);
INSERT INTO LISTAS_ARTISTA (COD,nombreArtistico,NOM_CIUDAD,NOM_ESTADO_PROV, ID_PAIS) VALUES (59,'Madonna','Bay City','Míchigan',4);
INSERT INTO LISTAS_ARTISTA (COD,nombreArtistico,NOM_CIUDAD,NOM_ESTADO_PROV, ID_PAIS) VALUES (60,'Prince','Mineápolis','Minesota',4);
INSERT INTO LISTAS_ARTISTA (COD,nombreArtistico,NOM_CIUDAD,NOM_ESTADO_PROV, ID_PAIS) VALUES (61,'Whitney Houston','Newark','Nueva Jersey',5);
INSERT INTO LISTAS_ARTISTA (COD,nombreArtistico,NOM_CIUDAD,NOM_ESTADO_PROV, ID_PAIS) VALUES (62,'Backstreet Boys','Orlando','Florida',4);
INSERT INTO LISTAS_ARTISTA (COD,nombreArtistico,NOM_CIUDAD,NOM_ESTADO_PROV, ID_PAIS) VALUES (63,'Lady Gaga','Nueva York','Nueva York',4);
INSERT INTO LISTAS_ARTISTA (COD,nombreArtistico,NOM_CIUDAD,NOM_ESTADO_PROV, ID_PAIS) VALUES (64,'Neil Young and Crazy Horse','Los Ángeles','California',4);
INSERT INTO LISTAS_ARTISTA (COD,nombreArtistico,NOM_CIUDAD,NOM_ESTADO_PROV, ID_PAIS) VALUES (65,'Van Morrison','Belfast','Washington D. C.',4);
INSERT INTO LISTAS_ARTISTA (COD,nombreArtistico,NOM_CIUDAD,NOM_ESTADO_PROV, ID_PAIS) VALUES (66,'Little Feat','Los Ángeles','California',4);
INSERT INTO LISTAS_ARTISTA (COD,nombreArtistico,NOM_CIUDAD,NOM_ESTADO_PROV, ID_PAIS) VALUES (67,'Paul Simon','Newark','Nueva Jersey',5);
INSERT INTO LISTAS_ARTISTA (COD,nombreArtistico,NOM_CIUDAD,NOM_ESTADO_PROV, ID_PAIS) VALUES (68,'Dereck and The Dominos','Londres','Gran Londres',5);
INSERT INTO LISTAS_ARTISTA (COD,nombreArtistico,NOM_CIUDAD,NOM_ESTADO_PROV, ID_PAIS) VALUES (69,'Fleetwood Mac','Londres','Gran Londres',5);
INSERT INTO LISTAS_ARTISTA (COD,nombreArtistico,NOM_CIUDAD,NOM_ESTADO_PROV, ID_PAIS) VALUES (70,'The Traveling Wilburys','Malibú','California',4);
INSERT INTO LISTAS_ARTISTA (COD,nombreArtistico,NOM_CIUDAD,NOM_ESTADO_PROV, ID_PAIS) VALUES (71,'Pink Floyd','Londres','Gran Londres',5);
INSERT INTO LISTAS_ARTISTA (COD,nombreArtistico,NOM_CIUDAD,NOM_ESTADO_PROV, ID_PAIS) VALUES (72,'Bruce Springsteen','Long Branch','Nueva Jersey',5);
INSERT INTO LISTAS_ARTISTA (COD,nombreArtistico,NOM_CIUDAD,NOM_ESTADO_PROV, ID_PAIS) VALUES (73,'The Band','Toronto','Ontario',12);
INSERT INTO LISTAS_ARTISTA (COD,nombreArtistico,NOM_CIUDAD,NOM_ESTADO_PROV, ID_PAIS) VALUES (74,'The Kinks','Londres','Gran Londres',5);
INSERT INTO LISTAS_ARTISTA (COD,nombreArtistico,NOM_CIUDAD,NOM_ESTADO_PROV, ID_PAIS) VALUES (75,'Lou Reed','Brooklyn','Nueva York',4);
INSERT INTO LISTAS_ARTISTA (COD,nombreArtistico,NOM_CIUDAD,NOM_ESTADO_PROV, ID_PAIS) VALUES (76,'Eagles','Los Ángeles','California',4);
INSERT INTO LISTAS_ARTISTA (COD,nombreArtistico,NOM_CIUDAD,NOM_ESTADO_PROV, ID_PAIS) VALUES (77,'The Doors','Los Ángeles','California',4);
INSERT INTO LISTAS_ARTISTA (COD,nombreArtistico,NOM_CIUDAD,NOM_ESTADO_PROV, ID_PAIS) VALUES (78,'The Kingsmen','Portland','Oregón',4);
INSERT INTO LISTAS_ARTISTA (COD,nombreArtistico,NOM_CIUDAD,NOM_ESTADO_PROV, ID_PAIS) VALUES (79,'Don McLean','New Rochelle','Nueva York',4);
INSERT INTO LISTAS_ARTISTA (COD,nombreArtistico,NOM_CIUDAD,NOM_ESTADO_PROV, ID_PAIS) VALUES (80,'Karol G','Medellín','Antioquia',7);
INSERT INTO LISTAS_ARTISTA (COD,nombreArtistico,NOM_CIUDAD,NOM_ESTADO_PROV, ID_PAIS) VALUES (81,'Fred de Palma','Turín','Piamonte',9);
INSERT INTO LISTAS_ARTISTA (COD,nombreArtistico,NOM_CIUDAD,NOM_ESTADO_PROV, ID_PAIS) VALUES (82,'Nio Garcia','San Juan','Puerto Rico',4);
INSERT INTO LISTAS_ARTISTA (COD,nombreArtistico,NOM_CIUDAD,NOM_ESTADO_PROV, ID_PAIS) VALUES (83,'Ozuna','San Juan','Puerto Rico',4);
INSERT INTO LISTAS_ARTISTA (COD,nombreArtistico,NOM_CIUDAD,NOM_ESTADO_PROV, ID_PAIS) VALUES (84,'Jay Wheeler','Salinas','Puerto Rico',4);
INSERT INTO LISTAS_ARTISTA (COD,nombreArtistico,NOM_CIUDAD,NOM_ESTADO_PROV, ID_PAIS) VALUES (85,'Chema Rivas','Ítrabo','Granada',1);
INSERT INTO LISTAS_ARTISTA (COD,nombreArtistico,NOM_CIUDAD,NOM_ESTADO_PROV, ID_PAIS) VALUES (86,'J Balvin','Medellín','Antioquia',7);
INSERT INTO LISTAS_ARTISTA (COD,nombreArtistico,NOM_CIUDAD,NOM_ESTADO_PROV, ID_PAIS) VALUES (87,'Bad Bunny','Almirante Sur','Puerto Rico',4);
INSERT INTO LISTAS_ARTISTA (COD,nombreArtistico,NOM_CIUDAD,NOM_ESTADO_PROV, ID_PAIS) VALUES (88,'Sech','Río Abajo','Panamá',10);
INSERT INTO LISTAS_ARTISTA (COD,nombreArtistico,NOM_CIUDAD,NOM_ESTADO_PROV, ID_PAIS) VALUES (89,'Tones and I','Mount Martha','Victoria',11);
INSERT INTO LISTAS_ARTISTA (COD,nombreArtistico,NOM_CIUDAD,NOM_ESTADO_PROV, ID_PAIS) VALUES (90,'Kenny Rogers','Houston','Texas',4);
INSERT INTO LISTAS_ARTISTA (COD,nombreArtistico,NOM_CIUDAD,NOM_ESTADO_PROV, ID_PAIS) VALUES (91,'Loretta Lynn','Butcker Hollow','Kentucky',4);
INSERT INTO LISTAS_ARTISTA (COD,nombreArtistico,NOM_CIUDAD,NOM_ESTADO_PROV, ID_PAIS) VALUES (92,'George Strait','Poteet','Texas',4);
INSERT INTO LISTAS_ARTISTA (COD,nombreArtistico,NOM_CIUDAD,NOM_ESTADO_PROV, ID_PAIS) VALUES (93,'Bob Wills','Kosse','Texas',4);
INSERT INTO LISTAS_ARTISTA (COD,nombreArtistico,NOM_CIUDAD,NOM_ESTADO_PROV, ID_PAIS) VALUES (94,'Glen Campbell','Nashville','Tennessee',4);
INSERT INTO LISTAS_ARTISTA (COD,nombreArtistico,NOM_CIUDAD,NOM_ESTADO_PROV, ID_PAIS) VALUES (95,'Kitty Wells','Nashville','Tennessee',4);
INSERT INTO LISTAS_ARTISTA (COD,nombreArtistico,NOM_CIUDAD,NOM_ESTADO_PROV, ID_PAIS) VALUES (96,'Hank Williams','Mount Olive','Alabama',4);
INSERT INTO LISTAS_ARTISTA (COD,nombreArtistico,NOM_CIUDAD,NOM_ESTADO_PROV, ID_PAIS) VALUES (97,'Bill Monroe','Rosine','Kentucky',4);
INSERT INTO LISTAS_ARTISTA (COD,nombreArtistico,NOM_CIUDAD,NOM_ESTADO_PROV, ID_PAIS) VALUES (98,'Buck Owens','Sherman','Texas',4);
INSERT INTO LISTAS_ARTISTA (COD,nombreArtistico,NOM_CIUDAD,NOM_ESTADO_PROV, ID_PAIS) VALUES (99,'The Stanley Brothers','Dickenson County','Virginia',4);
INSERT INTO LISTAS_ARTISTA (COD,nombreArtistico,NOM_CIUDAD,NOM_ESTADO_PROV, ID_PAIS) VALUES (100,'Waylon Jennings','Littlefield','Texas',4);
INSERT INTO LISTAS_ARTISTA (COD,nombreArtistico,NOM_CIUDAD,NOM_ESTADO_PROV, ID_PAIS) VALUES (101,'Dolly Parton','Sevierville','Tennessee',4);
INSERT INTO LISTAS_ARTISTA (COD,nombreArtistico,NOM_CIUDAD,NOM_ESTADO_PROV, ID_PAIS) VALUES (102,'Merle Haggard','Bakersfield','California',4);
INSERT INTO LISTAS_ARTISTA (COD,nombreArtistico,NOM_CIUDAD,NOM_ESTADO_PROV, ID_PAIS) VALUES (103,'Tammy Wynette','Itawamba','Misisipi',4);
INSERT INTO LISTAS_ARTISTA (COD,nombreArtistico,NOM_CIUDAD,NOM_ESTADO_PROV, ID_PAIS) VALUES (104,'Jimmie Rodgers','Nueva York','Nueva York',4);
INSERT INTO LISTAS_ARTISTA (COD,nombreArtistico,NOM_CIUDAD,NOM_ESTADO_PROV, ID_PAIS) VALUES (105,'George Jones','Vidor','Texas',4);
INSERT INTO LISTAS_ARTISTA (COD,nombreArtistico,NOM_CIUDAD,NOM_ESTADO_PROV, ID_PAIS) VALUES (107,'Patsy Cline','Winchester','Virginia',4);
INSERT INTO LISTAS_ARTISTA (COD,nombreArtistico,NOM_CIUDAD,NOM_ESTADO_PROV, ID_PAIS) VALUES (108,'Johnny Cash','Kingsland','Arkansas',4);
INSERT INTO LISTAS_ARTISTA (COD,nombreArtistico,NOM_CIUDAD,NOM_ESTADO_PROV, ID_PAIS) VALUES (109,'Aless Gibaja','Madrid','Madrid',1);
INSERT INTO LISTAS_ARTISTA (COD,nombreArtistico,NOM_CIUDAD,NOM_ESTADO_PROV, ID_PAIS) VALUES (110,'Karmele Marchante','Tortosa','Tarragona',1);
INSERT INTO LISTAS_ARTISTA (COD,nombreArtistico,NOM_CIUDAD,NOM_ESTADO_PROV, ID_PAIS) VALUES (111,'John Cobra','Sagunto','Valencia',1);
INSERT INTO LISTAS_ARTISTA (COD,nombreArtistico,NOM_CIUDAD,NOM_ESTADO_PROV, ID_PAIS) VALUES (112,'Pupi Poisson','Mandalgobi','Dundgovi',3);
INSERT INTO LISTAS_ARTISTA (COD,nombreArtistico,NOM_CIUDAD,NOM_ESTADO_PROV, ID_PAIS) VALUES (113,'Kiko Rivera','Sevilla','Sevilla',1);
INSERT INTO LISTAS_ARTISTA (COD,nombreArtistico,NOM_CIUDAD,NOM_ESTADO_PROV, ID_PAIS) VALUES (114,'Flos Mariae','Sant Jordi Desvalls','Girona',1);
INSERT INTO LISTAS_ARTISTA (COD,nombreArtistico,NOM_CIUDAD,NOM_ESTADO_PROV, ID_PAIS) VALUES (115,'Lory Money','Dakar','Dakar',2);
INSERT INTO LISTAS_ARTISTA (COD,nombreArtistico,NOM_CIUDAD,NOM_ESTADO_PROV, ID_PAIS) VALUES (116,'La Ogra','Gran Canaria','Las Palmas de Gran Canaria', 1);
INSERT INTO LISTAS_ARTISTA (COD,nombreArtistico,NOM_CIUDAD,NOM_ESTADO_PROV, ID_PAIS) VALUES (117,'Leticia Sabater','Barcelona','Barcelona',1);
INSERT INTO LISTAS_ARTISTA (COD,nombreArtistico,NOM_CIUDAD,NOM_ESTADO_PROV, ID_PAIS) VALUES (118,'Rodolfo Chikilicuatre','Barcelona','Barcelona',1);
INSERT INTO LISTAS_ARTISTA (COD,nombreArtistico,NOM_CIUDAD,NOM_ESTADO_PROV, ID_PAIS) VALUES (119,'Hoobastank','Agoura Hills','California',4);
INSERT INTO LISTAS_ARTISTA (COD,nombreArtistico,NOM_CIUDAD,NOM_ESTADO_PROV, ID_PAIS) VALUES (120,'Wet Wet Wet','Clydebank','Escocia',5);
INSERT INTO LISTAS_ARTISTA (COD,nombreArtistico,NOM_CIUDAD,NOM_ESTADO_PROV, ID_PAIS) VALUES (121,'Tizziano Ferro','Latina','Latina',9);




INSERT INTO LISTAS_GRUPO (COD, FCREACION) VALUES (2,STR_TO_DATE('01-01-1980','%d-%m-%Y'));
INSERT INTO LISTAS_GRUPO (COD, FCREACION) VALUES (3,STR_TO_DATE('01-01-1967','%d-%m-%Y'));
INSERT INTO LISTAS_GRUPO (COD, FCREACION,FDISOLUCION) VALUES (4,STR_TO_DATE('01-01-1992','%d-%m-%Y'),STR_TO_DATE('01-01-2006','%d-%m-%Y'));
INSERT INTO LISTAS_GRUPO (COD, FCREACION,FDISOLUCION) VALUES (5,STR_TO_DATE('01-01-1985','%d-%m-%Y'),null);
INSERT INTO LISTAS_GRUPO (COD, FCREACION,FDISOLUCION) VALUES (6,STR_TO_DATE('01-01-1976','%d-%m-%Y'),null);
INSERT INTO LISTAS_GRUPO (COD, FCREACION,FDISOLUCION) VALUES (8,STR_TO_DATE('01-01-1976','%d-%m-%Y'),STR_TO_DATE('01-01-1986','%d-%m-%Y'));
INSERT INTO LISTAS_GRUPO (COD, FCREACION,FDISOLUCION) VALUES (11,STR_TO_DATE('01-01-1982','%d-%m-%Y'),STR_TO_DATE('01-01-1987','%d-%m-%Y'));
INSERT INTO LISTAS_GRUPO (COD, FCREACION,FDISOLUCION) VALUES (12,STR_TO_DATE('01-01-1974','%d-%m-%Y'),STR_TO_DATE('01-01-1996','%d-%m-%Y'));
INSERT INTO LISTAS_GRUPO (COD, FCREACION,FDISOLUCION) VALUES (14,STR_TO_DATE('01-01-1968','%d-%m-%Y'),STR_TO_DATE('04-12-1980','%d-%m-%Y'));
INSERT INTO LISTAS_GRUPO (COD, FCREACION,FDISOLUCION) VALUES (15,STR_TO_DATE('01-01-1980','%d-%m-%Y'),STR_TO_DATE('01-01-2011','%d-%m-%Y'));
INSERT INTO LISTAS_GRUPO (COD, FCREACION,FDISOLUCION) VALUES (17,STR_TO_DATE('01-01-1981','%d-%m-%Y'),STR_TO_DATE('01-01-2002','%d-%m-%Y'));
INSERT INTO LISTAS_GRUPO (COD, FCREACION,FDISOLUCION) VALUES (18,STR_TO_DATE('01-01-1964','%d-%m-%Y'),STR_TO_DATE('01-01-1990','%d-%m-%Y'));
INSERT INTO LISTAS_GRUPO (COD, FCREACION,FDISOLUCION) VALUES (19,STR_TO_DATE('01-01-1975','%d-%m-%Y'),STR_TO_DATE('01-01-1978','%d-%m-%Y'));
INSERT INTO LISTAS_GRUPO (COD, FCREACION,FDISOLUCION) VALUES (21,STR_TO_DATE('01-01-1960','%d-%m-%Y'),STR_TO_DATE('09-04-1970','%d-%m-%Y'));
INSERT INTO LISTAS_GRUPO (COD, FCREACION,FDISOLUCION) VALUES (22,STR_TO_DATE('01-01-1966','%d-%m-%Y'),STR_TO_DATE('01-01-1970','%d-%m-%Y'));
INSERT INTO LISTAS_GRUPO (COD, FCREACION,FDISOLUCION) VALUES (26,STR_TO_DATE('01-01-1964','%d-%m-%Y'),null);
INSERT INTO LISTAS_GRUPO (COD, FCREACION,FDISOLUCION) VALUES (28,STR_TO_DATE('01-01-1987','%d-%m-%Y'),STR_TO_DATE('01-01-1994','%d-%m-%Y'));
INSERT INTO LISTAS_GRUPO (COD, FCREACION,FDISOLUCION) VALUES (29,STR_TO_DATE('01-01-1961','%d-%m-%Y'),null);
INSERT INTO LISTAS_GRUPO (COD, FCREACION,FDISOLUCION) VALUES (33,STR_TO_DATE('01-01-1962','%d-%m-%Y'),null);
INSERT INTO LISTAS_GRUPO (COD, FCREACION, FDISOLUCION) VALUES (38, STR_TO_DATE('01/01/2003', '%d/%m/%Y'), NULL);
INSERT INTO LISTAS_GRUPO (COD, FCREACION,FDISOLUCION) VALUES (39,STR_TO_DATE('01/01/2001','%d/%m/%Y'), Null);
INSERT INTO LISTAS_GRUPO (COD, FCREACION,FDISOLUCION) VALUES (44,STR_TO_DATE('14-08-1997','%d-%m-%Y'),STR_TO_DATE('02-02-2011','%d-%m-%Y'));
INSERT INTO LISTAS_GRUPO (COD, FCREACION,FDISOLUCION) VALUES (46,STR_TO_DATE('01-01-2000','%d-%m-%Y'),null);
INSERT INTO LISTAS_GRUPO (COD, FCREACION,FDISOLUCION) VALUES (49,STR_TO_DATE('01-01-1998','%d-%m-%Y'),null);
INSERT INTO LISTAS_GRUPO (COD, FCREACION,FDISOLUCION) VALUES (55,STR_TO_DATE('02-02-1982','%d-%m-%Y'),null);
INSERT INTO LISTAS_GRUPO (COD, FCREACION,FDISOLUCION) VALUES (57,STR_TO_DATE('12-10-1993','%d-%m-%Y'),null);
INSERT INTO LISTAS_GRUPO (COD, FCREACION,FDISOLUCION) VALUES (62,STR_TO_DATE('20-04-1993','%d-%m-%Y'),null);
INSERT INTO LISTAS_GRUPO (COD, FCREACION,FDISOLUCION) VALUES (64,STR_TO_DATE('01-01-1962','%d-%m-%Y'),null);
INSERT INTO LISTAS_GRUPO (COD, FCREACION,FDISOLUCION) VALUES (66,STR_TO_DATE('01-01-1969','%d-%m-%Y'),null);
INSERT INTO LISTAS_GRUPO (COD, FCREACION,FDISOLUCION) VALUES (68,STR_TO_DATE('01-01-1970','%d-%m-%Y'),STR_TO_DATE('01-01-1971','%d-%m-%Y'));
INSERT INTO LISTAS_GRUPO (COD, FCREACION,FDISOLUCION) VALUES (69,STR_TO_DATE('01-01-1967','%d-%m-%Y'),null);
INSERT INTO LISTAS_GRUPO (COD, FCREACION,FDISOLUCION) VALUES (70,STR_TO_DATE('01-01-1988','%d-%m-%Y'),STR_TO_DATE('01-01-1990','%d-%m-%Y'));
INSERT INTO LISTAS_GRUPO (COD, FCREACION,FDISOLUCION) VALUES (71,STR_TO_DATE('01-01-1965','%d-%m-%Y'),STR_TO_DATE('01-01-1995','%d-%m-%Y'));
INSERT INTO LISTAS_GRUPO (COD, FCREACION,FDISOLUCION) VALUES (73,STR_TO_DATE('01-01-1968','%d-%m-%Y'),STR_TO_DATE('01-01-1999','%d-%m-%Y'));
INSERT INTO LISTAS_GRUPO (COD, FCREACION,FDISOLUCION) VALUES (74,STR_TO_DATE('01-01-1963','%d-%m-%Y'),null);
INSERT INTO LISTAS_GRUPO (COD, FCREACION,FDISOLUCION) VALUES (76,STR_TO_DATE('01-01-1971','%d-%m-%Y'),null);
INSERT INTO LISTAS_GRUPO (COD, FCREACION,FDISOLUCION) VALUES (77,STR_TO_DATE('01-01-1965','%d-%m-%Y'),STR_TO_DATE('01-01-1973','%d-%m-%Y'));
INSERT INTO LISTAS_GRUPO (COD, FCREACION,FDISOLUCION) VALUES (78,STR_TO_DATE('01-01-1959','%d-%m-%Y'),null);
INSERT INTO LISTAS_GRUPO (COD, FCREACION,FDISOLUCION) VALUES (99,STR_TO_DATE('01-01-1946','%d-%m-%Y'),STR_TO_DATE('01-01-1966','%d-%m-%Y'));
INSERT INTO LISTAS_GRUPO (COD, FCREACION,FDISOLUCION) VALUES (114,STR_TO_DATE('12-01-2013','%d-%m-%Y'),null);
INSERT INTO LISTAS_GRUPO (COD, FCREACION,FDISOLUCION) VALUES (119,STR_TO_DATE('20-02-1994','%d-%m-%Y'),null);
INSERT INTO LISTAS_GRUPO (COD, FCREACION,FDISOLUCION) VALUES (120,STR_TO_DATE('25-05-1982','%d-%m-%Y'),null);



INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (1,'Catherine Bush',STR_TO_DATE('30-06-1958','%d-%m-%Y'),null);
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (7,'Kanye Omari West',STR_TO_DATE('08-05-1977','%d-%m-%Y'),null);
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (9,'Montero Lamar Hill',STR_TO_DATE('09-04-1999','%d-%m-%Y'),null);
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (10,'Taylor Alison Swift',STR_TO_DATE('13-12-1989','%d-%m-%Y'),null);
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (13,'Elvis Aaron Presley',STR_TO_DATE('08-01-1935','%d-%m-%Y'),STR_TO_DATE('16-08-1977','%d-%m-%Y'));
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (16,'Charles Anderson Edward Berry',STR_TO_DATE('18-10-1926','%d-%m-%Y'),STR_TO_DATE('18-03-2017','%d-%m-%Y'));
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (20,'Britney Jean Spears',STR_TO_DATE('02-12-1981','%d-%m-%Y'),null);
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (24,'Robert Allen Zimmerman',STR_TO_DATE('24-05-1941','%d-%m-%Y'),null);
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (25,'Samuel Cook',STR_TO_DATE('21-01-1931','%d-%m-%Y'),STR_TO_DATE('11-12-1964','%d-%m-%Y'));
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (27,'Ray Charles Robinson',STR_TO_DATE('23-09-1930','%d-%m-%Y'),STR_TO_DATE('10-06-2004','%d-%m-%Y'));
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (30,'Aretha Louise Franklin',STR_TO_DATE('25-03-1942','%d-%m-%Y'),STR_TO_DATE('16-08-2018','%d-%m-%Y'));
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (31,'Marvin Pentz Gay',STR_TO_DATE('02-04-1939','%d-%m-%Y'),STR_TO_DATE('01-04-1984','%d-%m-%Y'));
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (32,'John Winston Lennon',STR_TO_DATE('09-09-1940','%d-%m-%Y'),STR_TO_DATE('08-12-1980','%d-%m-%Y'));
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (34,'Amy Jade Winehouse',STR_TO_DATE('14-09-1983','%d-%m-%Y'), STR_TO_DATE('23-07-2011','%d-%m-%Y'));

INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (35,'Robin Miriam Carlsson',STR_TO_DATE('12/06/1979','%d/%m/%Y'), null);
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (36,'David Robert Jones',STR_TO_DATE('08/01/1947','%d/%m/%Y'), STR_TO_DATE('10/01/2016','%d/%m/%Y'));
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (37,'Melissa Arnette Elliott',STR_TO_DATE('01/07/1971','%d/%m/%Y'),null);
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (40,'Kendric Lamar Duckworth',STR_TO_DATE('17/06/1987','%d/%m/%Y'),null);
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (41,'Kelly Brianne Clarkson',STR_TO_DATE('24/04/1982','%d/%m/%Y'),null);
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (42,'Beyoncé Giselle Knowles-Carter',STR_TO_DATE('04-09-1981','%d-%m-%Y'),NULL);
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (43,'Mathangi Arulpragasam',STR_TO_DATE('18-07-1975','%d-%m-%Y'),null);
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (45,'Shawn Corey Carter',STR_TO_DATE('04-12-1969','%d-%m-%Y'),null);
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (47,'Adele Laurie Blue Adkins',STR_TO_DATE('05-05-1988','%d-%m-%Y'),null);
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (48,'Ella Marija Lani Yelich O''Connor',STR_TO_DATE('07/11/1996','%d/%m/%Y'),null);
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (51,'Edward Christopher Sheeran',STR_TO_DATE('17-02-1991','%d-%m-%Y'),NULL);
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (52,'Katheryn Elizabeth Hudson',STR_TO_DATE('25-10-1984','%d-%m-%Y'),NULL);
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (53,'Justin Drew Bieber',STR_TO_DATE('01-03-1994','%d-%m-%Y'),NULL);
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (54,'Shakira Isabel Mebarak Ripoll',STR_TO_DATE('02-02-1977','%d-%m-%Y'),NULL);
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (56,'Peter Gene Hernández',STR_TO_DATE('08-10-1985','%d-%m-%Y'),NULL);
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (58,'Michael Joseph Jackson',STR_TO_DATE('29-08-1958','%d-%m-%Y'),STR_TO_DATE('25-07-2009','%d-%m-%Y'));
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (59,'Madonna Louise Veronica Ciccone',STR_TO_DATE('16-08-1958','%d-%m-%Y'),null);
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (60,'Prince Rogers Nelson',STR_TO_DATE('07-06-1958','%d-%m-%Y'),STR_TO_DATE('21-04-2016','%d-%m-%Y'));
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (61,'Whitney Elizabeth Houston',STR_TO_DATE('09-08-1963','%d-%m-%Y'),STR_TO_DATE('11-02-2012','%d-%m-%Y'));
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (63,'Stefani Joanne Angelina Germanotta',STR_TO_DATE('28-03-1986','%d-%m-%Y'),null);
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (65,'George Ivan Morrison', STR_TO_DATE('31/08/1945','%d/%m/%Y'), null);
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (67,'Paul Frederic Simon', STR_TO_DATE('01/01/1956','%d/%m/%Y'), null);
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (72,'Bruce Frederick Joseph Springsteen', STR_TO_DATE('23-09-1949','%d-%m-%Y'), null);
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (75,'Lewis Allan Reed', STR_TO_DATE('02-03-1942','%d-%m-%Y'), STR_TO_DATE('27-10-2013','%d-%m-%Y'));
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (79,'Donald McLean II', STR_TO_DATE('02-10-1945','%d-%m-%Y'), null);
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (80,'Carolina Giraldo Navarro', STR_TO_DATE('14-02-1991','%d-%m-%Y'), null);
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (81,'Federico Palana', STR_TO_DATE('03-11-1989','%d-%m-%Y'), null);
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (82,'Luis Antonio Quinones Garcia', STR_TO_DATE('03-04-1989','%d-%m-%Y'), null);
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (83,'Juan Carlos Ozuna Rosado',STR_TO_DATE('13-03-1992','%d-%m-%Y'), null);
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (84,'José �?ngel López Martínez', STR_TO_DATE('25-04-1994','%d-%m-%Y'), null);
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (85,'Chema Rivas', STR_TO_DATE('01-01-2001','%d-%m-%Y'), null);
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (86,'José �?lvaro Osorio Balvín', STR_TO_DATE('07-05-1985','%d-%m-%Y'), null);
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (87,'Benito Antonio Martínez', STR_TO_DATE('10-03-1994','%d-%m-%Y'), null);
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (88,'Carlos Isaías Morales',STR_TO_DATE('03-12-1993','%d-%m-%Y'), null);
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (89,'Toni Watson', STR_TO_DATE('01-01-1990','%d-%m-%Y'), null);
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (90,'Kenneth Donald Rogers', STR_TO_DATE('21-08-1938','%d-%m-%Y'), STR_TO_DATE('20-03-2020','%d-%m-%Y'));
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (91,'Loretta Webb', STR_TO_DATE('14-04-1932','%d-%m-%Y'), null);
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (92,'George Harvey Strait', STR_TO_DATE('18-05-1952','%d-%m-%Y'), null);
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (93,'James Robert Wills', STR_TO_DATE('06-03-1905','%d-%m-%Y'), STR_TO_DATE('13-05-1975','%d-%m-%Y'));
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (94,'Glen Travis Campbell', STR_TO_DATE('22-04-1936','%d-%m-%Y'), STR_TO_DATE('08-08-2017','%d-%m-%Y'));
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (95,'Ellen Muriel Deason', STR_TO_DATE('30-08-1919','%d-%m-%Y'), STR_TO_DATE('16-07-2012','%d-%m-%Y'));
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (96,'Hiram King Williams', STR_TO_DATE('17-09-1923','%d-%m-%Y'), STR_TO_DATE('01-01-1953','%d-%m-%Y'));
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (97,'William Smith Monroe', STR_TO_DATE('13-09-1911','%d-%m-%Y'), STR_TO_DATE('09-09-1996','%d-%m-%Y'));
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (98,'Alvis Edgar Owens Jr.', STR_TO_DATE('12-08-1929','%d-%m-%Y'), STR_TO_DATE('25-03-2006','%d-%m-%Y'));
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (100,'Waylon Arnold Jennings', STR_TO_DATE('15-06-1937','%d-%m-%Y'), STR_TO_DATE('13-02-2002','%d-%m-%Y'));
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (101,'Dolly Rebecca Parton', STR_TO_DATE('19-01-1946','%d-%m-%Y'), null);
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (102,'Merle Ronald Haggard', STR_TO_DATE('06-04-1937','%d-%m-%Y'), STR_TO_DATE('06-04-2016','%d-%m-%Y'));
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (103,'Virginia Wynette Pugh', STR_TO_DATE('05-05-1942','%d-%m-%Y'), STR_TO_DATE('06-04-1998','%d-%m-%Y'));
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (104,'James Charles Rodgers', STR_TO_DATE('08-09-1897','%d-%m-%Y'), STR_TO_DATE('26-05-1933','%d-%m-%Y'));
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (105,'George Glenn Jones', STR_TO_DATE('12-09-1931','%d-%m-%Y'), STR_TO_DATE('26-04-2013','%d-%m-%Y'));
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (107,'Virginia Patterson Hensley', STR_TO_DATE('08-09-1932','%d-%m-%Y'), STR_TO_DATE('05-03-1963','%d-%m-%Y'));
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (108,'J. R. Cash', STR_TO_DATE('26-02-1932','%d-%m-%Y'), STR_TO_DATE('12-09-2003','%d-%m-%Y'));
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (109,'Aless Gibaja', STR_TO_DATE('19-04-1984','%d-%m-%Y'),null);
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (110,'María del Carmen Marchante Barrobés', STR_TO_DATE('15-09-1946','%d-%m-%Y'),null);
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (111,'Mario Vaquero Garcés', STR_TO_DATE('11-02-1978','%d-%m-%Y'),null);
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (112,'Alberto Zimmer', STR_TO_DATE('01-06-1983','%d-%m-%Y'),null);
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (113,'Francisco José Rivera Pantoja', STR_TO_DATE('09-02-1984','%d-%m-%Y'),null);
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (115,'Dara Dia', STR_TO_DATE('26-12-1978','%d-%m-%Y'),null);

INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (117,'Leticia Maria Sabater Alonso', STR_TO_DATE('21-06-1966','%d-%m-%Y'),null);
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (118,'David Fernandez Ortiz', STR_TO_DATE('24-06-1970','%d-%m-%Y'),null);
INSERT INTO LISTAS_ARTISTAIND (COD,NOMBREREAL,FNAC,FMUERTE) VALUES (121,'Tizziano Ferro', STR_TO_DATE('21-02-1980','%d-%m-%Y'),null);



INSERT INTO LISTAS_GENERO (COD, NOMBRE) VALUES (1,'Art pop');
INSERT INTO LISTAS_GENERO (COD, NOMBRE) VALUES (2,'Synth pop');
INSERT INTO LISTAS_GENERO (COD, NOMBRE) VALUES (3,'Pop');
INSERT INTO LISTAS_GENERO (COD, NOMBRE) VALUES (4,'Hip-hop');
INSERT INTO LISTAS_GENERO (COD, NOMBRE) VALUES (5,'Funk');
INSERT INTO LISTAS_GENERO (COD, NOMBRE) VALUES (6,'Rock Alternativo');
INSERT INTO LISTAS_GENERO (COD, NOMBRE) VALUES (7,'Grunge');
INSERT INTO LISTAS_GENERO (COD, NOMBRE) VALUES (8,'Trip-hop');
INSERT INTO LISTAS_GENERO (COD, NOMBRE) VALUES (9,'New wave');
INSERT INTO LISTAS_GENERO (COD, NOMBRE) VALUES (10,'Surf punk');
INSERT INTO LISTAS_GENERO (COD, NOMBRE) VALUES (11,'Punk rock');
INSERT INTO LISTAS_GENERO (COD, NOMBRE) VALUES (12,'Country');
INSERT INTO LISTAS_GENERO (COD, NOMBRE) VALUES (13,'Trap');
INSERT INTO LISTAS_GENERO (COD, NOMBRE) VALUES (14,'Reggae');
INSERT INTO LISTAS_GENERO (COD, NOMBRE) VALUES (15,'Punk');
INSERT INTO LISTAS_GENERO (COD, NOMBRE) VALUES (16,'Rock');
INSERT INTO LISTAS_GENERO (COD, NOMBRE) VALUES (17,'Indie');
INSERT INTO LISTAS_GENERO (COD, NOMBRE) VALUES (18,'Chamber pop');
INSERT INTO LISTAS_GENERO (COD, NOMBRE) VALUES (19,'Pop Rock');
INSERT INTO LISTAS_GENERO (COD, NOMBRE) VALUES (20,'Rock and roll');
INSERT INTO LISTAS_GENERO (COD, NOMBRE) VALUES (21,'Folk');
INSERT INTO LISTAS_GENERO (COD, NOMBRE) VALUES (22,'Soul');
INSERT INTO LISTAS_GENERO (COD, NOMBRE) VALUES (23,'Rhythm and blues');
INSERT INTO LISTAS_GENERO (COD, NOMBRE) VALUES (24,'Acústico');
INSERT INTO LISTAS_GENERO (COD, NOMBRE) VALUES (25,'Dance-pop');
INSERT INTO LISTAS_GENERO (COD, NOMBRE) VALUES (26,'Electro-pop');
INSERT INTO LISTAS_GENERO (COD, NOMBRE) VALUES (27,'Electronic dance');
INSERT INTO LISTAS_GENERO (COD, NOMBRE) VALUES (28,'Dirty rap');
INSERT INTO LISTAS_GENERO (COD, NOMBRE) VALUES (29,'Disco rock');
INSERT INTO LISTAS_GENERO (COD, NOMBRE) VALUES (30,'Kraut-rock');
INSERT INTO LISTAS_GENERO (COD, NOMBRE) VALUES (31,'Techno');
INSERT INTO LISTAS_GENERO (COD, NOMBRE) VALUES (32,'Reggaeton');
INSERT INTO LISTAS_GENERO (COD, NOMBRE) VALUES (33,'Disco');
INSERT INTO LISTAS_GENERO (COD, NOMBRE) VALUES (34,'Country rock');
INSERT INTO LISTAS_GENERO (COD, NOMBRE) VALUES (35,'Blugrass');
INSERT INTO LISTAS_GENERO (COD, NOMBRE) VALUES (36,'Pop Católico');




INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (1,'Wuthering Heights',1978,1);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (2,'Dreaming of Me',1981,2);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (3,'The Letter',1967,3);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (4,'Player’s Ball',1993,4);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (5,'Creep',1993,5);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (6,'Rock Lobster',1978,6);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (7,'Through the Wire',2003,7);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (8,'White Riot',1977,8);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (9,'Old Town Road',2019,9);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (10,'Tim McGraw',2006,10);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (11,'Hand in Glove',1984,11);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (12,'Blitzkrieg Bop',1976,12);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (13,'Thats All Right',1956,13);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (14,'Good Times Bad Times',1969,14);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (15,'Radio Free Europe',1983,15);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (16,'Maybellene',1956,16);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (17,'Sucker M.C.s/Its Like That',1984,17);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (18,'I Want You Back',1969,18);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (19,'Anarchy in the U.K.',1977,19);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (20,'Baby One More Time',1998,20);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (21,'Yesterday',1965,21);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (22,'Let it be',1968,21);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (23,'Hound Dog',1956,13);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (24,'Purple Haze',1967,22);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (25,'I want to hold your hand',1963,21);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (26,'London Calling',1979,8);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (27,'Blowin in the Wind',1963,24);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (28,'A Change is Gonna Come',1964,25);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (29,'My generation',1965,26);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (30,'What’d I say',1959,27);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (31,'Smells like Teen Spirit',1991,28);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (32,'Hey Jude',1968,21);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (33,'Johnny B. Goode',1959,16);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (34,'Good Vibrations',1970,29);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (35,'Respect',1965,30);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (36,'Whats Going On',1971,31);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (37,'Imagine',1971,32);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (38,'(I Cant Get No) Satisfaction',1965,33);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (39,'Like a Rolling Stone',1965,24);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (40,'Rehab',2006,34);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (41,'Dancing On My Own', 2017,35);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (42,'Blackstar',2015,36);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (43,'Work it', 2002,37);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (44,'All My Friends', 2007,38);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (45,'Crazy', 2006,39);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (46,'Toxic', 2003,20);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (47,'Alright', 2015,40);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (48,'Since U Been Gone', 2004,41);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (49,'Get Ur Freak On', 2001,37);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (50,'Crazy in Love',2003,42);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (51,'Paper Planes',2007,43);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (52,'Seven Nation Army',2003,44);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (53,'Hey Ya!',2003,4);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (54,'99 Problems',2003,45);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (55,'Maps',2003,46);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (56,'Runaway',2010,7);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (57,'Rolling in the deep',2011,47);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (58,'Royals',2013,48);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (59,'Last Nite',2001,49);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (60,'Despacito',2019,50);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (61,'Shape of you',2017,51);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (62,'Firework',2019,52);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (63,'Sorry',2015,53);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (64,'Hips dont lie',2006,54);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (65,'Take on me',1985,55);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (66,'Uptown Funk',2014,56);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (67,'Get Lucky',2013,57);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (68,'Thriller',1982,58);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (69,'Like a Prayer',1989,59);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (70,'When Doves Cry',1984,60);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (71,'Wanna Dance With Somebody',1987,61);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (72,'Everybody',1997,62);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (73,'Poker Face',2008,63);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (74,'Single Ladies',2008,42);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (75,'Powderfinger',1979,64);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (76,'Into the mystic',1970,65);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (77,'Willin',1971,66);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (78,'Space Oddity',1969,36);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (79,'Suspicious Minds',1969,13);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (80,'Baba ORiley',1971,26);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (81,'Brown Sugar',1971,33);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (82,'American Tune',1973,67);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (83,'Layla',1970,68);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (84,'The Chain',1977,69);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (85,'Handle with care',1988,70);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (86,'Shine on you crazy diamond',1975,71);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (87,'Stairway to Heaven',1971,14);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (88,'Thunder Road',1975,72);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (89,'The Weight',1968,73);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (90,'Lola',1970,74);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (91,'A day in the life',1967,21);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (92,'Sweet Jane',1977,75);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (93,'Born to run',1975,72);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (94,'Hotel California',1976,76);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (95,'Light my Fire',1967,77);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (96,'Louie Louie',1963,78);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (97,'Wont get Fooled Again',1971,26);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (98,'Jailhouse Rock',1957,13);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (99,'American Pie',1971,79);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (100,'Tusa',2019,80);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (101,'Se iluminaba',2019,81);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (102,'La Jeepeta - Remix',2020,82);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (103,'Caramelo',2020,83);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (104,'La Curiosidad',2020,84);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (105,'Mil Tequilas',2020,85);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (106,'Morado',2020,86);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (107,'Safaera',2020,87);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (108,'Relación',2020,88);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (109,'Dance Monkey',2020,89);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (110,'The Gambler',1978,90);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (111,'Dont Come Home A Drinkin (With Lovin on Your Mind)',1966,91);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (112,'All My Exs Live in Texas',1987,92);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (113,'New San Antonio Rose',1940,93);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (114,'Witchita Lineman',1968,94);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (115,'It Wasn’t God Who Made Honky Tonk Angels',1952,95);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (116,'Settin’ the Woods on Fire',1952,96);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (117,'Blue Moon of Kentucky',1947,97);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (118,'Ive Got a Tiger By the Tail',1964,98);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (119,'Man of Constant Sorrow',1951,99);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (120,'Mammas, Dont Let Your Babies Grow Up to Be Cowboys',1978,100);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (121,'Jolene',1973,101);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (122,'Mama Tried',1968,102);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (123,'You Dont Know Me',1962,27);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (124,'Stand By Your Man',1968,103);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (125,'Standing on the Corner (Blue Yodel #9)',1930,104);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (126,'He Stopped Loving Her Today',1980,105);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (127,'I’m So Lonesome I Could Cry',1949,96);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (128,'Crazy',1961,107);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (129,'I Walk the Line',1956,108);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (130,'Sexy summer',2004,109);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (131,'Soy un tsunami',2010,110);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (132,'Carol',2012,111);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (133,'Putón verbenero',2015,112);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (134,'Dale',2015,113);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (135,'Amén',2015,114);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (136,'Ola k ase',2013,115);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (137,'Te borro del feisbuh',2015,116);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (138,'La Salchipapa',2016,117);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (139,'Baila el Chiki Chiki',2017,118);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (140,'The reason is you',2001,119);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (141,'Love Is All Around',1994,120);
INSERT INTO LISTAS_CANCION(COD,TITULO,ANYO,COD_ARTISTA) VALUES (142,'El regalo m�s grande',2010,121);




INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (1,1);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (2,2);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (3,3);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (4,4);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (4,5);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (5,6);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (5,7);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (5,8);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (6,9);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (6,10);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (7,4);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (8,11);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (8,9);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (8,14);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (9,12);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (9,13);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (9,4);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (10,12);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (11,3);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (12,15);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (13,16);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (14,16);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (15,16);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (16,20);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (17,4);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (18,3);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (19,17);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (20,3);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (21,18);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (22,19);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (23,20);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (24,16);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (25,19);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (26,16);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (27,21);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (28,22);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (29,16);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (30,23);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (30,22);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (31,6);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (31,11);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (31,7);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (32,3);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (32,19);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (33,20);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (33,16);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (33,3);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (34,3);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (35,22);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (36,22);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (36,5);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (37,16);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (38,16);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (39,24);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (40,3);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (41,25);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (41,26);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (42,27);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (42,16);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (43,4);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (43,28);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (44,29);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (44,30);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (44,16);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (44,17);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (45,3);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (45,22);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (45,6);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (46,27);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (46,3);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (47,22);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (47,4);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (48,3);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (49,27);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (50,23);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (50,3);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (51,4);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (51,17);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (51,25);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (51,3);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (52,6);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (53,4);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (53,5);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (53,3);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (54,4);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (55,25);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (55,19);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (55,17);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (56,4);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (57,22);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (57,3);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (58,1);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (58,8);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (58,31);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (59,16);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (59,17);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (60,32);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (60,3);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (61,3);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (61,21);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (61,16);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (62,25);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (62,26);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (62,27);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (62,2);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (63,3);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (64,32);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (65,2);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (65,9);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (66,3);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (66,5);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (66,9);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (66,33);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (67,33);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (67,5);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (68,5);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (69,3);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (70,2);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (71,3);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (72,3);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (73,3);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (74,3);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (74,25);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (75,16);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (76,34);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (77,16);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (77,34);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (78,2);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (79,19);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (80,30);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (81,16);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (82,16);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (83,16);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (84,16);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (85,16);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (85,21);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (86,16);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (87,16);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (88,16);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (89,19);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (90,19);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (91,6);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (92,20);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (93,16);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (94,16);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (94,34);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (94,21);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (95,2);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (96,16);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (97,16);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (97,2);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (98,16);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (99,16);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (100,3);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (100,32);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (101,32);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (101,4);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (102,32);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (103,32);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (104,32);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (105,32);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (105,3);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (106,32);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (107,32);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (108,32);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (109,3);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (109,26);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (109,17);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (109,25);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (110,12);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (110,34);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (110,3);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (111,12);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (111,34);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (112,12);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (113,12);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (114,12);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (115,12);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (116,12);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (117,35);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (117,12);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (118,12);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (119,12);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (119,35);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (120,12);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (121,12);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (122,12);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (123,12);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (124,12);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (125,12);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (126,12);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (127,12);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (128,12);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (129,12);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (130,33);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (131,3);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (132,28);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (133,3);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (134,3);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (135,36);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (136,13);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (136,4);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (137,3);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (138,3);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (139,3);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (139,32);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (140,19);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (141,3);
INSERT INTO LISTAS_GENERO_CANCION (COD_CANCION,COD_GENERO) VALUES (142,3);




INSERT INTO LISTAS_LISTA (COD,NOMBRE,ANYO,FUENTE,AUTOR) VALUES (1,'Mejores debuts RollingStone',2020,'https://los40.com/los40/2020/05/21/los40classic/1590052156_938806.html', 'Rolling Stone');

INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (1,1,20);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (2,1,19);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (3,1,18);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (4,1,17);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (5,1,16);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (6,1,15);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (7,1,14);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (8,1,13);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (9,1,12);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (10,1,11);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (11,1,10);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (12,1,9);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (13,1,8);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (14,1,7);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (15,1,6);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (16,1,5);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (17,1,4);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (19,1,3);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (18,1,2);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (20,1,1);




INSERT INTO LISTAS_LISTA (COD,NOMBRE,ANYO,FUENTE,AUTOR) VALUES (2,'Las 20 imprescindibles de todos los tiempos',2019,'https://www.esquirelat.com/cultura/20-mejores-canciones-de-todos-los-tiempos/', 'Esquire');

INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (21,2,13);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (22,2,20);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (23,2,19);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (16,2,18);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (24,2,17);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (25,2,16);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (26,2,15);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (27,2,14);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (28,2,12);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (29,2,11);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (30,2,10);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (31,2,9);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (32,2,8);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (33,2,7);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (34,2,6);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (35,2,5);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (36,2,4);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (37,2,3);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (38,2,2);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (39,2,1);


INSERT INTO LISTAS_LISTA (COD,NOMBRE,ANYO,FUENTE,AUTOR) VALUES (3,'Las mejores canciones del siglo',2018,'https://www.lanacion.com','Rolling Stone');

INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (40,3,20);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (41,3,19);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (42,3,18);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (43,3,17);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (44,3,16);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (45,3,15);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (46,3,14);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (47,3,13);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (48,3,11);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (49,3,12);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (50,3,1);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (51,3,2);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (52,3,3);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (53,3,4);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (54,3,5);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (55,3,6);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (56,3,7);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (57,3,8);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (58,3,9);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (59,3,10);




INSERT INTO LISTAS_LISTA (COD,NOMBRE,ANYO,FUENTE,AUTOR) VALUES (4,'Temazos frikis made in Spain',2015,'https://www.elespanol.com/social/20170324/203230101_0.html','El Español');


INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (130,4,1);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (131,4,2);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (132,4,3);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (133,4,4);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (134,4,5);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (135,4,6);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (136,4,7);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (137,4,8);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (138,4,9);
INSERT INTO LISTAS_POSICION_LISTA (COD_CANCION,COD_LISTA,POSICION) VALUES (139,4,10);

-- comprobación con select

SELECT * FROM LISTAS_ARTISTA;
SELECT * FROM LISTAS_ARTISTAIND;
SELECT * FROM LISTAS_CANCION;
SELECT * FROM LISTAS_CIUDAD;
SELECT * FROM LISTAS_ESTADO_PROVINCIA;
SELECT * FROM LISTAS_GENERO;
SELECT * FROM LISTAS_GENERO_CANCION;
SELECT * FROM LISTAS_GRUPO;
SELECT * FROM LISTAS_LISTA;
SELECT * FROM LISTAS_PAIS;
SELECT * FROM LISTAS_POSICION_LISTA;


